import type { Product } from "../types"

export const arcHeatProtectionProducts: Product[] = [
  {
    id: "ahp-001",
    name: "ECO ARC-10",
    category: "arc-heat-protection",
    subcategory: "Economic Arc Shields",
    brand: "Paulson International",
    description: "Economic arc flash face shield providing 10 cal/cm² protection",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/AMP2-12-HTS-2.jpg",
    features: ["10 cal/cm² protection", "Lightweight design", "Cost-effective", "NFPA 70E compliant"],
    applications: ["Arc flash protection", "Electrical work", "Switchgear operations", "Low voltage work"],
  },
  {
    id: "ahp-002",
    name: "AMP1-E2S-HT-PCT-EC",
    category: "arc-heat-protection",
    subcategory: "AmpShield Series",
    brand: "Paulson International",
    description: "Helmet-mounted arc shield with enhanced side protection and heat resistance",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/AMP2-12-HTS-2.jpg",
    features: ["Enhanced side coverage", "Heat resistant", "Helmet mounted", "PCT coating", "EC rated"],
    applications: ["Arc flash work", "Electrical maintenance", "High voltage operations", "Industrial electrical"],
  },
  {
    id: "ahp-003",
    name: "AMP1-12-HTS",
    category: "arc-heat-protection",
    subcategory: "AmpShield Series",
    brand: "Paulson International",
    description: "12 cal/cm² arc flash helmet-mounted shield with hard coat",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/AMP2-12-HTS-2.jpg",
    features: ["12 cal/cm² protection", "Hard coat finish", "Helmet mounted", "Scratch resistant", "ATPV rated"],
    applications: ["Medium voltage work", "Arc flash zones", "Electrical panels", "Transformer work"],
  },
  {
    id: "ahp-004",
    name: "IM22-AFA2-40-V-HT",
    category: "arc-heat-protection",
    subcategory: "Arc Shields for Hoods",
    brand: "Paulson International",
    description: "40 cal/cm² arc flash shield designed for hood integration with heat resistance",
    image: "https://udyogisafety.com/wp-content/uploads/2020/03/IM22-AFA2-40-V.jpg",
    features: ["40 cal/cm² protection", "Hood integration", "Heat resistant", "High visibility", "ATPV rated"],
    applications: ["High voltage work", "Arc flash Category 4", "Switchgear", "Electrical substations"],
  },
  {
    id: "ahp-005",
    name: "IM22-AFA2-75-V-HT",
    category: "arc-heat-protection",
    subcategory: "Arc Shields for Hoods",
    brand: "Paulson International",
    description: "75 cal/cm² arc flash shield for extreme protection requirements",
    image: "https://udyogisafety.com/wp-content/uploads/2020/03/IM22-AFA2-40-V.jpg",
    features: [
      "75 cal/cm² protection",
      "Extreme protection",
      "Hood compatible",
      "High heat resistance",
      "ATPV certified",
    ],
    applications: [
      "Extreme arc flash zones",
      "High energy electrical work",
      "Power generation",
      "Critical infrastructure",
    ],
  },
  {
    id: "ahp-006",
    name: "IM22-AFA2-100-V-HT",
    category: "arc-heat-protection",
    subcategory: "Arc Shields for Hoods",
    brand: "Paulson International",
    description: "Maximum 100 cal/cm² arc flash protection for highest risk environments",
    image: "https://udyogisafety.com/wp-content/uploads/2020/03/IM22-AFA2-40-V.jpg",
    features: ["100 cal/cm² protection", "Maximum protection rating", "Heavy-duty construction", "Heat and arc rated"],
    applications: ["Extreme hazard zones", "High energy electrical work", "Power plants", "Critical maintenance"],
  },
  {
    id: "ahp-007",
    name: "QV9GS5-6",
    category: "arc-heat-protection",
    subcategory: "QuickView Welding Shields",
    brand: "Paulson International",
    description: "QuickView welding shield with shade 5-6 flip-up lens for gas welding",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/AMP2-12-HTS-2.jpg",
    features: [
      "Shade 5-6 flip lens",
      "QuickView design",
      "Gas welding rated",
      "Heat resistant",
      "Flip-up functionality",
    ],
    applications: ["Gas welding", "Oxy-fuel cutting", "Brazing", "Torch operations"],
  },
  {
    id: "ahp-008",
    name: "QV96GHCFM-2",
    category: "arc-heat-protection",
    subcategory: "Metalized Heat Shields",
    brand: "Paulson International",
    description: "Gold-green heat reflective metalized face shield for extreme heat environments",
    image: "https://udyogisafety.com/wp-content/uploads/2020/03/IM22-AFA2-40-V.jpg",
    features: [
      "Gold-green coating",
      "Heat reflective",
      "Radiant heat protection",
      "Flip-up design",
      "Metalized finish",
    ],
    applications: ["Foundries", "Glass manufacturing", "Metal casting", "High heat environments"],
  },
  {
    id: "ahp-009",
    name: "QVGHCF5-6",
    category: "arc-heat-protection",
    subcategory: "QuickView Heat Shields",
    brand: "Paulson International",
    description: "Gold heat reflective face shield with shade 5-6 protection",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/AMP2-12-HTS-2.jpg",
    features: ["Gold coating", "Shade 5-6 protection", "Heat reflective", "QuickView system", "Full face coverage"],
    applications: ["Furnace operations", "Metal pouring", "Hot work", "Foundry work"],
  },
  {
    id: "ahp-010",
    name: "IM9-L6F",
    category: "arc-heat-protection",
    subcategory: "High Temperature Shields",
    brand: "Paulson International",
    description: "Lightweight 10-inch high temperature face shield for furnace operations",
    image: "https://udyogisafety.com/wp-content/uploads/2020/03/IM22-AFA2-40-V.jpg",
    features: [
      "10-inch coverage",
      "Lightweight design",
      "High temperature rated",
      "Shade 6 lens",
      "Durable construction",
    ],
    applications: ["Furnace watching", "Kiln operations", "Glass work", "High heat industrial"],
  },
  {
    id: "ahp-011",
    name: "CB6-HD",
    category: "arc-heat-protection",
    subcategory: "Face Shield Carriers",
    brand: "Paulson International",
    description: "Heavy-duty cap bracket carrier for mounting face shields to hard hats",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/AMP2-12-HTS-2.jpg",
    features: ["Heavy-duty bracket", "Cap mounted", "Universal fit", "Durable construction", "Easy attachment"],
    applications: ["Industrial mounting", "Shield attachment", "Hard hat integration", "General use"],
  },
  {
    id: "ahp-012",
    name: "CB2-HD",
    category: "arc-heat-protection",
    subcategory: "Face Shield Carriers",
    brand: "Paulson International",
    description: "Standard cap bracket for face shield mounting with headband",
    image: "https://udyogisafety.com/wp-content/uploads/2020/03/IM22-AFA2-40-V.jpg",
    features: ["Standard bracket", "Headband compatible", "Adjustable fit", "Reliable mounting", "Cost-effective"],
    applications: ["Face shield mounting", "Headband systems", "Industrial use", "General protection"],
  },
  {
    id: "ahp-013",
    name: "QV9CS7-6",
    category: "arc-heat-protection",
    subcategory: "QuickView Welding Shields",
    brand: "Paulson International",
    description: "QuickView shade 7-6 welding shield for heavy welding operations",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/AMP2-12-HTS-2.jpg",
    features: ["Shade 7-6 protection", "Heavy welding rated", "QuickView flip-up", "Dark lens", "Heat resistant"],
    applications: ["Heavy arc welding", "High amperage welding", "Industrial welding", "Metal fabrication"],
  },
]
