import type { Product } from "../types"

export const arcHeatProtectionProducts: Product[] = [
  {
    id: "arc-001",
    name: "Economic Arc Shield",
    category: "arc-heat-protection",
    subcategory: "Arc Shields",
    brand: "Udyogi Safety",
    description: "Budget-friendly arc welding shield for basic welding operations",
    image: "/images/products/economic-arc-shield.jpg",
    features: ["Cost-effective", "Fixed shade lens", "Basic protection", "Adjustable headband", "Lightweight"],
    applications: ["Basic welding", "Training", "Light fabrication", "General use"],
  },
  {
    id: "arc-002",
    name: "AmpShield 400",
    category: "arc-heat-protection",
    subcategory: "Arc Shields",
    brand: "Udyogi Safety",
    description: "Professional arc shield rated for 400 amp welding operations",
    image: "/images/products/ampshield-400.jpg",
    features: ["400 amp rated", "Professional grade", "Comfortable fit", "Durable construction", "Wide viewing area"],
    applications: ["Heavy welding", "Industrial fabrication", "Professional use", "High amperage work"],
  },
  {
    id: "arc-003",
    name: "AmpShield 600",
    category: "arc-heat-protection",
    subcategory: "Arc Shields",
    brand: "Udyogi Safety",
    description: "Heavy-duty arc shield for high amperage welding up to 600 amps",
    image: "/images/products/ampshield-600.jpg",
    features: ["600 amp rated", "Heavy-duty protection", "Extended coverage", "Professional grade", "Heat resistant"],
    applications: ["Heavy industrial welding", "High amperage operations", "Shipyards", "Heavy fabrication"],
  },
  {
    id: "arc-004",
    name: "Arc Shield for Hood",
    category: "arc-heat-protection",
    subcategory: "Arc Shields",
    brand: "Udyogi Safety",
    description: "Arc shield designed to integrate with safety hoods",
    image: "/images/products/arc-shield-hood.jpg",
    features: ["Hood integration", "Flip-up design", "Comfortable wear", "Arc protection", "Versatile use"],
    applications: ["Welding with hood", "Multi-protection needs", "Industrial settings", "Confined spaces"],
  },
  {
    id: "arc-005",
    name: "QuickView Welding Shield",
    category: "arc-heat-protection",
    subcategory: "Arc Shields",
    brand: "Udyogi Safety",
    description: "Quick flip-up welding shield for improved productivity",
    image: "/images/products/quickview-shield.jpg",
    features: ["Quick flip mechanism", "Easy lens changes", "Ergonomic design", "Productivity focused", "Durable"],
    applications: ["Production welding", "Fabrication shops", "Manufacturing", "Repetitive welding"],
  },
  {
    id: "arc-006",
    name: "Metalized Heat Shield",
    category: "arc-heat-protection",
    subcategory: "Heat Shields",
    brand: "Udyogi Safety",
    description: "Reflective metalized shield for extreme heat protection",
    image: "/images/products/metalized-heat-shield.jpg",
    features: [
      "Heat reflective",
      "Metalized coating",
      "Extreme heat protection",
      "Durable construction",
      "Professional grade",
    ],
    applications: ["Foundries", "Glass manufacturing", "Metal casting", "High heat environments"],
  },
  {
    id: "arc-007",
    name: "Aluminized Heat Shield",
    category: "arc-heat-protection",
    subcategory: "Heat Shields",
    brand: "Udyogi Safety",
    description: "Aluminized protective shield for radiant heat reflection",
    image: "/images/products/aluminized-heat-shield.jpg",
    features: ["Aluminized fabric", "Radiant heat reflection", "Splash protection", "Lightweight", "Flexible"],
    applications: ["Foundry work", "Metal pouring", "Furnace operations", "Hot work"],
  },
  {
    id: "arc-008",
    name: "Face Shield Carrier with Arc Protection",
    category: "arc-heat-protection",
    subcategory: "Accessories",
    brand: "Udyogi Safety",
    description: "Universal carrier frame compatible with arc shields",
    image: "/images/products/arc-carrier.jpg",
    features: ["Universal compatibility", "Adjustable fit", "Comfortable padding", "Durable frame", "Arc rated"],
    applications: ["Welding", "Fabrication", "Industrial work", "Multi-shield use"],
  },
  {
    id: "arc-009",
    name: "Leather Neck Shield",
    category: "arc-heat-protection",
    subcategory: "Accessories",
    brand: "Udyogi Safety",
    description: "Leather neck protection shield for welding operations",
    image: "/images/products/leather-neck-shield.jpg",
    features: ["Genuine leather", "Neck protection", "Heat resistant", "Comfortable wear", "Durable"],
    applications: ["Welding", "Grinding", "Hot work", "Fabrication"],
  },
  {
    id: "arc-010",
    name: "Welding Blanket",
    category: "arc-heat-protection",
    subcategory: "Heat Protection",
    brand: "Udyogi Safety",
    description: "Fire-resistant welding blanket for spark and spatter protection",
    image: "/images/products/welding-blanket.jpg",
    features: ["Fire resistant", "Spark protection", "Heavy-duty fabric", "Large coverage", "Reusable"],
    applications: ["Welding protection", "Grinding", "Cutting", "Hot work areas"],
  },
  {
    id: "arc-011",
    name: "Heat Resistant Apron",
    category: "arc-heat-protection",
    subcategory: "Heat Protection",
    brand: "Udyogi Safety",
    description: "Heavy-duty heat resistant apron for welding and hot work",
    image: "/images/products/heat-apron.jpg",
    features: ["Heat resistant material", "Adjustable straps", "Full body coverage", "Durable", "Comfortable"],
    applications: ["Welding", "Foundry work", "Metal work", "Hot material handling"],
  },
  {
    id: "arc-012",
    name: "Welding Sleeves",
    category: "arc-heat-protection",
    subcategory: "Arm Protection",
    brand: "Udyogi Safety",
    description: "Protective sleeves for arm protection during welding",
    image: "/images/products/welding-sleeves.jpg",
    features: ["Heat resistant", "Arm coverage", "Comfortable fit", "Elastic ends", "Durable fabric"],
    applications: ["Welding", "Grinding", "Hot work", "Fabrication"],
  },
  {
    id: "arc-013",
    name: "Arc Flash Hood",
    category: "arc-heat-protection",
    subcategory: "Arc Shields",
    brand: "Udyogi Safety",
    description: "Protective hood with arc flash protection for electrical work",
    image: "/images/products/arc-flash-hood.jpg",
    features: [
      "Arc flash rated",
      "Head and neck protection",
      "Flame resistant",
      "Comfortable fit",
      "Professional grade",
    ],
    applications: ["Electrical work", "Arc flash zones", "High voltage operations", "Switchgear work"],
  },
]
