import type { Product } from "../types"

export const eyeProtectionProducts: Product[] = [
  {
    id: "ep-001",
    name: "UD 71",
    category: "eye-protection",
    subcategory: "Safety Goggles",
    brand: "Udyogi Safety",
    description: "Clear vision safety goggles with anti-fog coating and wrap-around protection",
    image: "https://udyogisafety.com/wp-content/uploads/2020/12/181025-146-UD-71-Smoke-Smoke-AF-2048x2048.jpg",
    features: ["Anti-fog lens", "UV protection", "Adjustable strap", "Indirect ventilation", "Impact resistant"],
    applications: ["Chemical handling", "Laboratory work", "Grinding operations", "Dust environments"],
  },
  {
    id: "ep-002",
    name: "UD 81",
    category: "eye-protection",
    subcategory: "Safety Goggles",
    brand: "Udyogi Safety",
    description: "Professional welding goggles with flip-up design for versatile protection",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/181025-122-UD-81-Clear-2048x2048.jpg",
    features: ["Flip-up design", "Impact resistant", "Comfortable fit", "Durable frame"],
    applications: ["Gas welding", "Cutting operations", "Brazing", "Industrial work"],
  },
  {
    id: "ep-003",
    name: "UD 90",
    category: "eye-protection",
    subcategory: "Safety Goggles",
    brand: "Udyogi Safety",
    description: "Wrap-around safety goggles for maximum side protection",
    image: "https://udyogisafety.com/wp-content/uploads/2020/12/UD-90-af-600x600-1.jpg",
    features: ["Wrap-around design", "Scratch resistant", "UV protection", "Lightweight"],
    applications: ["Construction", "Manufacturing", "General industrial", "Outdoor work"],
  },
  {
    id: "ep-004",
    name: "UD 91",
    category: "eye-protection",
    subcategory: "Safety Goggles",
    brand: "Udyogi Safety",
    description: "Premium safety goggles with enhanced optical clarity",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/181025-170-UD-91-Clear-2048x2048.jpg",
    features: ["High optical clarity", "Anti-scratch coating", "Adjustable temples", "Side shields"],
    applications: ["Precision work", "Inspection", "Quality control", "Assembly"],
  },
  {
    id: "ep-005",
    name: "Ultra-Z",
    category: "eye-protection",
    subcategory: "Safety Glasses",
    brand: "Udyogi Safety",
    description: "Z87+ rated wraparound safety glasses for high impact protection",
    image: "/images/products/ultra-z-glasses.jpg",
    features: ["Z87+ rated", "Impact protection", "Wraparound design", "Lightweight", "Comfortable fit"],
    applications: ["High impact areas", "Construction", "Manufacturing", "Automotive"],
  },
  {
    id: "ep-006",
    name: "Ultra Edge",
    category: "eye-protection",
    subcategory: "Safety Glasses",
    brand: "Udyogi Safety",
    description: "Stylish safety glasses with edge-to-edge lens protection",
    image: "https://udyogisafety.com/wp-content/uploads/2023/06/Ultra-Edge-Clear.jpg",
    features: ["Edge seal design", "Comfort temples", "Anti-scratch", "Modern styling", "UV protection"],
    applications: ["Office safety", "Labs", "Light industry", "Inspection work"],
  },
  {
    id: "ep-007",
    name: "Ultra Sports",
    category: "eye-protection",
    subcategory: "Safety Glasses",
    brand: "Udyogi Safety",
    description: "Sports-style safety glasses combining comfort with industrial protection",
    image: "/images/products/ultra-sports-glasses.jpg",
    features: ["Sport design", "Secure fit", "Impact rated", "Modern look", "Wraparound lens"],
    applications: ["Active work environments", "Outdoor operations", "Sports facilities", "Recreation areas"],
  },
  {
    id: "ep-008",
    name: "UD 46",
    category: "eye-protection",
    subcategory: "Safety Goggles",
    brand: "Udyogi Safety",
    description: "Clear lens safety goggles with excellent visibility and comfort",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/150720-13544-UD-46-Clear-2048x2048.jpg",
    features: ["Clear lens", "Comfortable fit", "Adjustable strap", "Good ventilation"],
    applications: ["General industry", "Workshops", "Assembly", "Multi-purpose use"],
  },
  {
    id: "ep-009",
    name: "UD 46 IR- Blue",
    category: "eye-protection",
    subcategory: "IR Protection",
    brand: "Udyogi Safety",
    description: "Blue tinted IR protection goggles for welding and hot work",
    image: "/images/products/ud46-ir-blue-goggles.jpg",
    features: ["IR protection", "Blue tint filter", "Anti-scratch", "Comfortable fit", "Welding rated"],
    applications: ["Welding", "Hot work", "Furnace operations", "Metal work"],
  },
  {
    id: "ep-010",
    name: "UD 46 IR- Green",
    category: "eye-protection",
    subcategory: "IR Protection",
    brand: "Udyogi Safety",
    description: "Green tinted IR protection goggles for superior glare reduction",
    image: "/images/products/ud46-ir-green-goggles.jpg",
    features: ["IR protection", "Green tint filter", "Welding rated", "Durable frame", "Side shields"],
    applications: ["Gas welding", "Brazing", "Soldering", "Cutting operations"],
  },
  {
    id: "ep-011",
    name: "Edge Vision",
    category: "eye-protection",
    subcategory: "Safety Glasses",
    brand: "Edge",
    description: "Modern safety glasses with panoramic vision and edge protection",
    image: "https://udyogisafety.com/wp-content/uploads/2020/06/181025-299-Edge-vision-clear-AF-1-2048x2048.jpg",
    features: ["Panoramic lens", "Anti-scratch coating", "Side shields", "Lightweight frame", "UV protection"],
    applications: ["General industry", "Workshops", "Quality control", "Inspection work"],
  },
  {
    id: "ep-012",
    name: "Edge Trax",
    category: "eye-protection",
    subcategory: "Safety Glasses",
    brand: "Edge",
    description: "Professional-grade safety glasses for all-day comfort and protection",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/181025-299-Edge-Trax-1-2048x2048.jpg",
    features: ["Professional grade", "All-day comfort", "Clear optics", "Durable construction"],
    applications: ["Professional trades", "Contractors", "Maintenance work", "Service industry"],
  },
  {
    id: "ep-013",
    name: "Crystal Plus",
    category: "eye-protection",
    subcategory: "Safety Glasses",
    brand: "Udyogi Safety",
    description: "Crystal clear vision safety glasses with superior optical quality",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/181025-355-Crystal-Plus-2048x2048.jpg",
    features: ["Crystal clear lens", "Lightweight", "Comfort fit", "UV protection", "Premium optics"],
    applications: ["Precision work", "Assembly", "Electronics", "Clean rooms"],
  },
  {
    id: "ep-014",
    name: "UD 50",
    category: "eye-protection",
    subcategory: "Safety Goggles",
    brand: "Udyogi Safety",
    description: "Versatile safety goggles suitable for multiple industrial applications",
    image: "https://udyogisafety.com/wp-content/uploads/2021/09/181025-162-UD-50-clear-2-2048x2048.jpg",
    features: ["Versatile design", "Good ventilation", "Impact resistant", "Adjustable strap"],
    applications: ["Multi-purpose use", "Construction", "Manufacturing", "General safety"],
  },
  {
    id: "ep-015",
    name: "Twister",
    category: "eye-protection",
    subcategory: "Safety Glasses",
    brand: "Udyogi Safety",
    description: "Stylish wrap-around safety glasses with temple length adjustment",
    image: "https://udyogisafety.com/wp-content/uploads/2020/06/181025-194-Twister-2048x2048.jpg",
    features: ["Fashionable design", "Adjustable temples", "UV protection", "Hard coating", "Comfortable"],
    applications: ["General industry", "Inspection", "Light assembly", "Office work"],
  },
  {
    id: "ep-016",
    name: "Neolite",
    category: "eye-protection",
    subcategory: "Safety Glasses",
    brand: "Udyogi Safety",
    description: "Ultra-lightweight safety glasses for extended wear comfort",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/neo-lite.jpg",
    features: ["Ultra lightweight", "UV protection", "Scratch resistant", "Modern design", "Comfortable"],
    applications: ["General industry", "Inspection", "Assembly", "Quality control"],
  },
  {
    id: "ep-017",
    name: "Neolite Plus",
    category: "eye-protection",
    subcategory: "Safety Glasses",
    brand: "Udyogi Safety",
    description: "Enhanced Neolite with additional protective features and comfort",
    image: "https://udyogisafety.com/wp-content/uploads/2023/07/NEO-LITE-PLUS-1.jpg",
    features: ["Enhanced protection", "Anti-fog coating", "Adjustable temples", "Premium optics", "All-day comfort"],
    applications: ["Professional use", "Extended wear", "Variable conditions", "Multi-purpose"],
  },
  {
    id: "ep-018",
    name: "GW250",
    category: "eye-protection",
    subcategory: "Welding Goggles",
    brand: "Udyogi Safety",
    description: "Professional welding goggles with flip-up lens and side protection",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/1322799822.g250.jpg",
    features: ["Flip-up design", "Welding rated", "Comfortable headband", "Side protection", "Durable"],
    applications: ["Arc welding", "Gas welding", "Cutting", "Brazing"],
  },
  {
    id: "ep-019",
    name: "UD 39",
    category: "eye-protection",
    subcategory: "Safety Goggles",
    brand: "Udyogi Safety",
    description: "Sealed safety goggles for chemical splash and dust protection",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/181025-418-UD-39-2048x2048.jpg",
    features: ["Sealed design", "Chemical resistant", "Indirect ventilation", "Comfortable seal"],
    applications: ["Chemical handling", "Laboratory", "Pharmaceutical", "Dust environments"],
  },
  {
    id: "ep-020",
    name: "UD 49",
    category: "eye-protection",
    subcategory: "Safety Goggles",
    brand: "Udyogi Safety",
    description: "Enhanced protection goggles with superior seal and ventilation",
    image: "/images/products/ud49-goggles.jpg",
    features: ["Enhanced seal", "Better ventilation", "Anti-fog option", "Durable construction"],
    applications: ["Chemical plants", "Labs", "Processing", "Manufacturing"],
  },
  {
    id: "ep-021",
    name: "UD 31",
    category: "eye-protection",
    subcategory: "Safety Goggles",
    brand: "Udyogi Safety",
    description: "Compact safety goggles offering reliable protection at economy price",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/181025-426-UD-31-2048x2048.jpg",
    features: ["Compact design", "Lightweight", "Good seal", "Economical", "Reliable"],
    applications: ["General industry", "Labs", "Inspection", "Quality control"],
  },
  {
    id: "ep-022",
    name: "Galaxy Duos / Acetate",
    category: "eye-protection",
    subcategory: "Welding Goggles",
    brand: "Udyogi Safety",
    description: "Dual-lens welding goggles with acetate frame for maximum durability",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/1329703691.galaxy-duos.jpg",
    features: ["Dual lens design", "Acetate frame", "Welding protection", "Durable construction"],
    applications: ["Heavy welding", "Industrial welding", "Fabrication", "Metal work"],
  },
  {
    id: "ep-023",
    name: "Ultra View / XT",
    category: "eye-protection",
    subcategory: "Safety Glasses",
    brand: "Udyogi Safety",
    description: "Extra-tough safety glasses with panoramic wide-angle view",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/1221575726.ultra-view-product.jpg",
    features: ["Panoramic lens", "Extra tough", "Anti-fog", "UV protection", "Wide angle view"],
    applications: ["Construction", "Manufacturing", "Inspection", "Maintenance"],
  },
  {
    id: "ep-024",
    name: "Ultra View IR",
    category: "eye-protection",
    subcategory: "IR Protection",
    brand: "Udyogi Safety",
    description: "Infrared protection glasses with ultra-wide field of view",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/181025-949-Ultraview-IR-2048x2048.jpg",
    features: ["IR rated", "Ultra-wide view", "Heat protection", "Comfort fit", "Durable"],
    applications: ["Furnace operations", "Hot work", "Foundry", "Metal processing"],
  },
  {
    id: "ep-025",
    name: "UD 40",
    category: "eye-protection",
    subcategory: "Welding Goggles",
    brand: "Udyogi Safety",
    description: "Professional welding goggles with flip-up lens and superior comfort",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/Furnace-Watching-Glass-UD-40.jpg",
    features: ["Flip-up lens", "Welding rated", "Indirect ventilation", "Comfortable headband"],
    applications: ["Gas welding", "Oxy-acetylene", "Cutting", "Brazing"],
  },
  {
    id: "ep-026",
    name: "I 273 IR 5 / IR 2",
    category: "eye-protection",
    subcategory: "IR Protection",
    brand: "Udyogi Safety",
    description: "Dual-shade IR welding glasses with interchangeable IR 5 and IR 2 lenses",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/Safety-Spectacle.jpg",
    features: ["Dual shade option", "IR 5 and IR 2 lenses", "Interchangeable", "Professional grade"],
    applications: ["Variable welding work", "Inspection", "Furnace viewing", "Multi-purpose welding"],
  },
  {
    id: "ep-027",
    name: "I 273",
    category: "eye-protection",
    subcategory: "Safety Glasses",
    brand: "Udyogi Safety",
    description: "Professional safety glasses with superior optical clarity",
    image: "https://udyogisafety.com/wp-content/uploads/2020/04/1273-1.jpg",
    features: ["Professional grade", "Superior optics", "Comfortable", "Durable frame"],
    applications: ["Professional use", "Precision work", "Inspection", "Quality assurance"],
  },
  {
    id: "ep-028",
    name: "I 2371",
    category: "eye-protection",
    subcategory: "Safety Glasses",
    brand: "Udyogi Safety",
    description: "Advanced safety glasses with enhanced protection features",
    image: "https://udyogisafety.com/wp-content/uploads/2020/04/2371_Grey-2.jpg",
    features: ["Advanced design", "Enhanced protection", "Comfortable fit", "Anti-scratch"],
    applications: ["Industrial work", "Manufacturing", "Assembly", "General safety"],
  },
  {
    id: "ep-029",
    name: "UD 30",
    category: "eye-protection",
    subcategory: "Over Glasses",
    brand: "Udyogi Safety",
    description: "Over-glasses safety goggles that fit comfortably over prescription eyewear",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/181025-243-UD-30-clear-2048x2048.jpg",
    features: ["Over-glasses design", "Prescription compatible", "Full seal", "Universal fit"],
    applications: ["For prescription wearers", "Chemical handling", "Dusty work", "General protection"],
  },
  {
    id: "ep-030",
    name: "Ultra Over",
    category: "eye-protection",
    subcategory: "Over Glasses",
    brand: "Udyogi Safety",
    description: "Premium over-glasses protection with anti-fog coating",
    image: "https://udyogisafety.com/wp-content/uploads/2023/03/u7.jpg",
    features: ["Over-glasses fit", "Anti-fog coating", "Full seal", "Comfortable", "Universal size"],
    applications: ["Prescription eyewear users", "Laboratory", "Medical", "Research"],
  },
  {
    id: "ep-031",
    name: "Edge Over",
    category: "eye-protection",
    subcategory: "Over Glasses",
    brand: "Edge",
    description: "Edge-branded over-glasses with superior coverage and protection",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/181025-34-Edge-over-clear-2048x2048.jpg",
    features: ["Prescription compatible", "Side shields", "Clear optics", "Adjustable", "Full coverage"],
    applications: ["Labs", "Medical facilities", "Research", "General safety"],
  },
  {
    id: "ep-032",
    name: "Fogal",
    category: "eye-protection",
    subcategory: "Anti-Fog Goggles",
    brand: "Udyogi Safety",
    description: "Advanced anti-fog goggles with superior fog-free performance",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/200702-031-Fogal-2048x2048.jpg",
    features: ["Superior anti-fog", "Clear vision", "Sealed design", "Comfortable fit", "Fog-free guarantee"],
    applications: ["Cold storage", "Temperature changes", "Humid conditions", "Food processing"],
  },
]
