import type { Product } from "../types"

export const faceProtectionProducts: Product[] = [
  {
    id: "fp-001",
    name: "6PAV / 6PAU Helmet Mount",
    category: "face-protection",
    subcategory: "Helmet-Mounted Shields",
    brand: "Paulson",
    description: "Universal helmet-mounted face shield with flip-up functionality",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/1126104391.6pav.jpg",
    features: ["Helmet mounted", "Flip-up design", "Universal fit", "Durable construction"],
    applications: ["Grinding", "Chipping", "General industrial work", "Metal fabrication"],
  },
  {
    id: "fp-002",
    name: "6PA3",
    category: "face-protection",
    subcategory: "Helmet-Mounted Shields",
    brand: "Udyogi Safety",
    description: "Lightweight helmet-mounted face shield for general protection",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/6PA3.jpg",
    features: ["Lightweight design", "Helmet compatible", "Clear visor", "Easy mounting", "Impact resistant"],
    applications: ["General welding", "Grinding", "Metal work", "Construction"],
  },
  {
    id: "fp-003",
    name: "FC 38 B Shade 7",
    category: "face-protection",
    subcategory: "Welding Visors",
    brand: "Udyogi Safety",
    description: "Blue tinted shade 7 welding visor for heavy arc welding operations",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/FC-38-Carrier.jpg",
    features: ["Shade 7 protection", "Blue tint", "Arc welding rated", "Replaceable visor", "Adjustable headgear"],
    applications: ["Heavy arc welding", "High-intensity welding", "Professional welding", "Industrial fabrication"],
  },
  {
    id: "fp-004",
    name: "FC 38 G Shade 3",
    category: "face-protection",
    subcategory: "Welding Visors",
    brand: "Udyogi Safety",
    description: "Green tinted shade 3 welding visor for light gas welding and brazing",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/FC-38-Carrier.jpg",
    features: ["Shade 3 protection", "Green tint", "Gas welding rated", "Lightweight", "Comfortable fit"],
    applications: ["Gas welding", "Brazing", "Soldering", "Light cutting operations"],
  },
  {
    id: "fp-005",
    name: "FC 38 G Shade 5",
    category: "face-protection",
    subcategory: "Welding Visors",
    brand: "Udyogi Safety",
    description: "Green tinted shade 5 welding visor for medium intensity welding work",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/FC-38-Carrier.jpg",
    features: ["Shade 5 protection", "Green tint", "Medium welding rated", "Durable visor", "Adjustable"],
    applications: ["Medium welding", "Gas cutting", "Torch brazing", "Metal work"],
  },
  {
    id: "fp-006",
    name: "FC 38 B Shade 3",
    category: "face-protection",
    subcategory: "Welding Visors",
    brand: "Udyogi Safety",
    description: "Blue tinted shade 3 welding visor for light welding and inspection work",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/FC-38-Carrier.jpg",
    features: ["Shade 3 protection", "Blue tint", "Light welding", "Inspection use", "Comfortable headgear"],
    applications: ["Light welding", "Welding inspection", "Furnace observation", "Hot work monitoring"],
  },
  {
    id: "fp-007",
    name: "FC 38 C",
    category: "face-protection",
    subcategory: "Face Shields",
    brand: "Udyogi Safety",
    description: "Clear face shield visor for general face protection against impact and splash",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/FC-38-Carrier.jpg",
    features: [
      "Clear visor",
      "Full face coverage",
      "Impact resistant",
      "Chemical splash protection",
      "Anti-fog coating",
    ],
    applications: ["Grinding", "Chemical handling", "Splash protection", "General safety"],
  },
  {
    id: "fp-008",
    name: "FC 48",
    category: "face-protection",
    subcategory: "Face Shields",
    brand: "Udyogi Safety",
    description: "Professional face shield with enhanced protection and comfort features",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/743811801.fc48-g-fa-ce-shield-welding-1.jpg",
    features: ["Enhanced protection", "Professional grade", "Comfortable fit", "Durable construction", "Clear optics"],
    applications: ["Industrial work", "Manufacturing", "Professional trades", "Multi-purpose protection"],
  },
  {
    id: "fp-009",
    name: "FC 58",
    category: "face-protection",
    subcategory: "Face Shields",
    brand: "Udyogi Safety",
    description: "Full face protection shield with superior coverage and ventilation",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/983336534.fc-58-face-shield-1.jpg",
    features: ["Full face coverage", "Superior protection", "Good ventilation", "Impact resistant", "Adjustable"],
    applications: ["Heavy grinding", "Chemical plants", "Industrial safety", "High-risk operations"],
  },
  {
    id: "fp-010",
    name: "FC 1000",
    category: "face-protection",
    subcategory: "Face Shields",
    brand: "Udyogi Safety",
    description: "Premium face shield system with advanced features and maximum protection",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/FC-38-Carrier.jpg",
    features: ["Premium quality", "Maximum protection", "Advanced features", "Professional grade", "Superior comfort"],
    applications: ["Professional use", "Critical operations", "Laboratory work", "Medical applications"],
  },
  {
    id: "fp-011",
    name: "B1/B10R",
    category: "face-protection",
    subcategory: "Face Shield Carriers",
    brand: "Udyogi Safety",
    description: "Ratchet-type face shield carrier with adjustable fit and durable construction",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/1037402987.b10r-rat-chet-type-fa-ce-shield-carrier.jpg",
    features: ["Ratchet adjustment", "Durable plastic", "Universal fit", "Compatible with FC series", "Comfortable"],
    applications: ["Face shield mounting", "Industrial safety", "Multi-purpose carrier", "Professional use"],
  },
  {
    id: "fp-012",
    name: "A3",
    category: "face-protection",
    subcategory: "Face Shield Carriers",
    brand: "Udyogi Safety",
    description: "Flip-up face shield carrier with elasticated headband for easy use",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/A3-Carrier-2048x2048.jpg",
    features: ["Flip-up design", "Elastic headband", "Universal fit", "Lightweight", "Easy on/off"],
    applications: ["Quick protection", "Intermittent use", "General industry", "Multi-environment"],
  },
  {
    id: "fp-013",
    name: "AL3",
    category: "face-protection",
    subcategory: "Face Shield Carriers",
    brand: "Udyogi Safety",
    description: "Aluminum lightweight face shield carrier for extended wear comfort",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/A3-Carrier-2048x2048.jpg",
    features: [
      "Lightweight aluminum",
      "Extended wear comfort",
      "Durable construction",
      "Adjustable fit",
      "Professional grade",
    ],
    applications: ["Long duration work", "Professional trades", "Industrial use", "Extended operations"],
  },
  {
    id: "fp-014",
    name: "A8",
    category: "face-protection",
    subcategory: "Face Shield Carriers",
    brand: "Udyogi Safety",
    description: "Premium face shield carrier with superior comfort and adjustability",
    image: "https://udyogisafety.com/wp-content/uploads/2023/04/al8.jpg",
    features: ["Premium quality", "Superior comfort", "Multiple adjustments", "Durable design", "Professional use"],
    applications: ["Professional trades", "Extended use", "Heavy-duty work", "Industrial operations"],
  },
  {
    id: "fp-015",
    name: "FC 100",
    category: "face-protection",
    subcategory: "Face Shield Carriers",
    brand: "Udyogi Safety",
    description: "HDPE flip-up face shield carrier compatible with FC series shields",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/Carrier-FC-100.jpg",
    features: ["HDPE construction", "Flip-up design", "FC series compatible", "Slotted type", "Durable"],
    applications: ["Industrial safety", "Face shield mounting", "Multi-purpose use", "Professional operations"],
  },
  {
    id: "fp-016",
    name: "FC 200 Carrier",
    category: "face-protection",
    subcategory: "Face Shield Carriers",
    brand: "Udyogi Safety",
    description: "Heavy-duty ratchet type face shield carrier",
    image: "/images/products/fc-200-carrier.jpg",
    features: ["Ratchet adjustment", "Heavy-duty build", "Comfortable headband", "FC series compatible"],
    applications: ["Industrial work", "Grinding", "Metal work", "General protection"],
  },
]
