import type { Product } from "../types"

export const faceProtectionProducts: Product[] = [
  {
    id: "face-001",
    name: "UD90 Face Shield",
    category: "face-protection",
    subcategory: "Face Shields",
    brand: "Udyogi Safety",
    description: "Clear polycarbonate face shield with adjustable headgear for face and eye protection",
    image: "/images/products/ud90-face-shield.jpg",
    features: [
      "Clear polycarbonate visor",
      "Adjustable headgear",
      "Wide face coverage",
      "Scratch resistant",
      "Impact protection",
    ],
    applications: [
      "Chemical splash protection",
      "Grinding operations",
      "Medical procedures",
      "General industrial work",
    ],
  },
  {
    id: "face-002",
    name: "UD91 Arc Shield",
    category: "face-protection",
    subcategory: "Welding Shields",
    brand: "Udyogi Safety",
    description: "Welding face shield with flip-up visor for arc welding protection",
    image: "/images/products/ud91-arc-shield.jpg",
    features: [
      "Flip-up design",
      "Arc flash protection",
      "Adjustable headband",
      "Comfortable padding",
      "Durable construction",
    ],
    applications: ["Arc welding", "Metal cutting", "Grinding", "Fabrication work"],
  },
  {
    id: "face-003",
    name: "Paulson Arc Shield",
    category: "face-protection",
    subcategory: "Welding Shields",
    brand: "Paulson",
    description: "Professional arc welding shield with superior protection and comfort",
    image: "/images/products/paulson-arc-shield.jpg",
    features: [
      "Professional grade",
      "Excellent arc protection",
      "Lightweight design",
      "Adjustable fit",
      "Premium quality",
    ],
    applications: ["Professional welding", "Industrial fabrication", "Metal workshops", "Construction"],
  },
  {
    id: "face-004",
    name: "Clear Face Shield with Visor",
    category: "face-protection",
    subcategory: "Face Shields",
    brand: "Udyogi Safety",
    description: "Full-face clear shield with integrated visor attachment",
    image: "/images/products/clear-face-shield.jpg",
    features: ["Full face coverage", "Clear visibility", "Visor attachment", "Comfortable wear", "Easy to clean"],
    applications: ["Chemical handling", "Spray operations", "Medical use", "Food processing"],
  },
  {
    id: "face-005",
    name: "Mesh Face Shield",
    category: "face-protection",
    subcategory: "Face Shields",
    brand: "Udyogi Safety",
    description: "Metal mesh face shield for protection against flying particles and debris",
    image: "/images/products/mesh-face-shield.jpg",
    features: [
      "Steel mesh construction",
      "Excellent ventilation",
      "Impact protection",
      "Adjustable headgear",
      "Durable",
    ],
    applications: ["Grinding", "Cutting", "Forestry work", "Landscaping"],
  },
  {
    id: "face-006",
    name: "Helmet Mounted Face Shield",
    category: "face-protection",
    subcategory: "Face Shields",
    brand: "Udyogi Safety",
    description: "Face shield designed to attach directly to safety helmets",
    image: "/images/products/helmet-face-shield.jpg",
    features: ["Helmet mountable", "Easy attachment", "Flip-up design", "Compatible with most helmets", "Clear visor"],
    applications: ["Construction", "Forestry", "Mining", "Multi-hazard environments"],
  },
  {
    id: "face-007",
    name: "Welding Visor UD81",
    category: "face-protection",
    subcategory: "Welding Shields",
    brand: "Udyogi Safety",
    description: "Fixed shade welding visor for consistent arc protection",
    image: "/images/products/ud81-welding-goggles.jpg",
    features: ["Fixed shade lens", "Arc protection", "Comfortable headgear", "Durable frame", "Professional use"],
    applications: ["Gas welding", "Cutting", "Brazing", "Light fabrication"],
  },
  {
    id: "face-008",
    name: "Chin Guard",
    category: "face-protection",
    subcategory: "Accessories",
    brand: "Udyogi Safety",
    description: "Protective chin guard attachment for helmets",
    image: "/images/products/chin-guard.jpg",
    features: ["Helmet attachment", "Chin protection", "Adjustable fit", "Durable construction", "Easy installation"],
    applications: ["Forestry", "Construction", "Logging", "Chainsaw work"],
  },
  {
    id: "face-009",
    name: "Face Shield Carrier",
    category: "face-protection",
    subcategory: "Accessories",
    brand: "Udyogi Safety",
    description: "Universal face shield carrier frame with adjustable headgear",
    image: "/images/products/face-shield-carrier.jpg",
    features: [
      "Universal fit",
      "Adjustable headband",
      "Compatible with various shields",
      "Comfortable padding",
      "Durable",
    ],
    applications: ["General industry", "Construction", "Manufacturing", "Multiple hazard protection"],
  },
  {
    id: "face-010",
    name: "Auto-Darkening Welding Helmet",
    category: "face-protection",
    subcategory: "Welding Shields",
    brand: "Udyogi Safety",
    description: "Advanced auto-darkening welding helmet with adjustable shade settings",
    image: "/images/products/auto-darkening-helmet.jpg",
    features: ["Auto-darkening lens", "Adjustable shade 9-13", "Solar powered", "Grinding mode", "Lightweight design"],
    applications: ["MIG/TIG welding", "Arc welding", "Grinding", "Professional fabrication"],
  },
  {
    id: "face-011",
    name: "Leather Welding Hood",
    category: "face-protection",
    subcategory: "Welding Shields",
    brand: "Udyogi Safety",
    description: "Traditional leather welding hood for heavy-duty welding",
    image: "/images/products/leather-welding-hood.jpg",
    features: ["Genuine leather", "Heat resistant", "Fixed shade lens", "Durable construction", "Classic design"],
    applications: ["Arc welding", "Heavy fabrication", "Metal shops", "Traditional welding"],
  },
  {
    id: "face-012",
    name: "Flip-Front Welding Helmet",
    category: "face-protection",
    subcategory: "Welding Shields",
    brand: "Udyogi Safety",
    description: "Convenient flip-front welding helmet for easy lens access",
    image: "/images/products/flip-front-helmet.jpg",
    features: [
      "Flip-front design",
      "Easy lens replacement",
      "Comfortable headgear",
      "Impact resistant",
      "Professional grade",
    ],
    applications: ["Production welding", "Fabrication shops", "Manufacturing", "Industrial welding"],
  },
  {
    id: "face-013",
    name: "Face Shield Replacement Visor",
    category: "face-protection",
    subcategory: "Accessories",
    brand: "Udyogi Safety",
    description: "Replacement polycarbonate visor for face shields",
    image: "/images/products/replacement-visor.jpg",
    features: ["Clear polycarbonate", "Scratch resistant", "Universal fit", "Cost-effective", "Easy replacement"],
    applications: ["Maintenance", "Replacement parts", "Safety compliance", "General use"],
  },
  {
    id: "face-014",
    name: "Tinted Face Shield",
    category: "face-protection",
    subcategory: "Face Shields",
    brand: "Udyogi Safety",
    description: "Tinted face shield for outdoor work with sun protection",
    image: "/images/products/tinted-face-shield.jpg",
    features: ["UV protection", "Tinted visor", "Glare reduction", "Impact protection", "Outdoor use"],
    applications: ["Outdoor construction", "Road work", "Landscaping", "Sunny environments"],
  },
  {
    id: "face-015",
    name: "Wire Mesh Faceguard",
    category: "face-protection",
    subcategory: "Face Shields",
    brand: "Udyogi Safety",
    description: "Heavy-duty wire mesh faceguard for forestry and chainsaw work",
    image: "/images/products/wire-mesh-faceguard.jpg",
    features: ["Steel wire mesh", "Maximum ventilation", "Impact resistant", "Helmet mountable", "Forestry rated"],
    applications: ["Chainsaw operation", "Forestry work", "Logging", "Brushcutting"],
  },
  {
    id: "face-016",
    name: "Grinding Face Shield",
    category: "face-protection",
    subcategory: "Face Shields",
    brand: "Udyogi Safety",
    description: "Heavy-duty face shield specifically designed for grinding operations",
    image: "/images/products/grinding-face-shield.jpg",
    features: ["Impact rated", "Thick polycarbonate", "Wide coverage", "Comfortable headgear", "Grinding specific"],
    applications: ["Grinding", "Cutting", "Metal fabrication", "Heavy duty work"],
  },
]
