import type { Product } from "../types"

export const fallProtectionProducts: Product[] = [
  {
    id: "fp-001",
    name: "I EASY 310T3",
    category: "fall-protection",
    subcategory: "Carabiners",
    brand: "Irudek",
    description: "Pear-shaped aluminum carabiner with auto-locking gate for fall protection systems",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/i-easy-310t3.jpg",
    features: ["Auto-locking gate", "Aluminum construction", "Lightweight", "Pear-shaped", "High breaking strength"],
    applications: ["Fall arrest systems", "Anchorage points", "Rope systems", "Industrial climbing"],
  },
  {
    id: "fp-002",
    name: "I EDGE AP01 Single Pulley",
    category: "fall-protection",
    subcategory: "Pulleys",
    brand: "Irudek",
    description: "Single pulley system for efficient rope management and reduced friction in fall protection applications",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/i-edge-ap01-pulley.jpg",
    features: ["Single pulley design", "Reduced friction", "Aluminum construction", "Rated capacity", "Smooth operation"],
    applications: ["Rescue operations", "Rope systems", "Suspended access", "Height work"],
  },
  {
    id: "fp-003",
    name: "I EDGE AP02 Double Pulley",
    category: "fall-protection",
    subcategory: "Pulleys",
    brand: "Irudek",
    description: "Double pulley system providing enhanced mechanical advantage and efficient load distribution",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/i-edge-ap02-pulley.jpg",
    features: ["Double pulley system", "Mechanical advantage", "Heavy-duty construction", "Dual wheels", "High capacity"],
    applications: ["Rescue systems", "Heavy load handling", "Suspended access", "Emergency services"],
  },
  {
    id: "fp-004",
    name: "I EDGE AP101 Single Pulley",
    category: "fall-protection",
    subcategory: "Pulleys",
    brand: "Irudek",
    description: "Industrial-grade single pulley designed for professional rescue and fall protection operations",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/i-edge-ap101-pulley.jpg",
    features: ["Industrial-grade", "Single wheel design", "Certified capacity", "Durable materials", "Professional use"],
    applications: ["Professional rescue", "Industrial applications", "Height work", "Rigging systems"],
  },
  {
    id: "fp-005",
    name: "I EDGE D01 Hand Descender",
    category: "fall-protection",
    subcategory: "Descenders",
    brand: "Irudek",
    description: "Compact hand-operated descender for controlled descent in fall protection and rescue operations",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/i-edge-d01-descender.jpg",
    features: ["Hand-operated", "Controlled descent", "Compact design", "Smooth operation", "Safety-rated"],
    applications: ["Rope access", "Rescue operations", "Vertical descent", "Work positioning"],
  },
  {
    id: "fp-006",
    name: "I EDGE T1 Tandem Pulley",
    category: "fall-protection",
    subcategory: "Pulleys",
    brand: "Irudek",
    description: "Tandem configuration pulley system designed for complex rigging and high-load applications",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/i-edge-t1-tandem.jpg",
    features: ["Tandem configuration", "Dual-wheel setup", "High capacity", "Professional-grade", "Multiple attachment points"],
    applications: ["Complex rescue operations", "High-load systems", "Professional rigging", "Emergency services"],
  },
  {
    id: "fp-007",
    name: "I EDGE UCA 7004 Chest Ascender Pulley",
    category: "fall-protection",
    subcategory: "Ascenders",
    brand: "Irudek",
    description: "Chest-mounted ascender pulley system for efficient ascending operations and rope access work",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/i-edge-uea-7004.jpg",
    features: ["Chest-mounted design", "Efficient ascending", "Integrated pulley", "Comfortable wear", "Safety-rated"],
    applications: ["Rope access climbing", "Tower work", "Industrial ascent", "Rope training"],
  },
  {
    id: "fp-008",
    name: "I EDGE UHA 7002 Hand Ascender",
    category: "fall-protection",
    subcategory: "Ascenders",
    brand: "Irudek",
    description: "Hand ascender designed for safe and efficient upward movement along vertical ropes",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/i-edge-uha-7002.jpg",
    features: ["Hand-operated ascender", "Smooth climbing", "Comfortable grip", "Safety-rated", "Durable construction"],
    applications: ["Rope climbing", "Vertical access", "Tower maintenance", "Industrial climbing"],
  },
  {
    id: "fp-009",
    name: "I FIGURE OF 8 Descender",
    category: "fall-protection",
    subcategory: "Descenders",
    brand: "Irudek",
    description: "Classic figure-8 descender providing reliable friction-based descent control",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/i-figure-of-8.jpg",
    features: ["Figure-8 design", "Reliable friction", "Easy operation", "Versatile use", "Multiple grip positions"],
    applications: ["Rope descent", "Rescue operations", "Climbing", "Work positioning"],
  },
  {
    id: "fp-010",
    name: "Safety Net Corner",
    category: "fall-protection",
    subcategory: "Fall Prevention Nets",
    brand: "Irudek",
    description: "Corner attachment system for fall prevention safety nets in construction and industrial sites",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/safety-net-corner.jpg",
    features: ["Corner bracket", "Secure attachment", "Durable material", "Easy installation", "Multiple fixing points"],
    applications: ["Construction sites", "Platform safety", "Fall prevention", "Temporary structures"],
  },
  {
    id: "fp-011",
    name: "I UB 2004",
    category: "fall-protection",
    subcategory: "Harness Accessories",
    brand: "Irudek",
    description: "Harness connection point and accessory designed for compatible fall protection systems",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/i-ub-2004.jpg",
    features: ["Secure connection", "Compatible design", "Durable material", "Easy attachment", "Safety-rated"],
    applications: ["Harness systems", "Fall protection", "Anchorage connection", "Industrial safety"],
  },
  {
    id: "fp-012",
    name: "I UB 2005 SS",
    category: "fall-protection",
    subcategory: "Harness Accessories",
    brand: "Irudek",
    description: "Stainless steel harness accessory for harsh and corrosive environments",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/i-ub-2005-ss.jpg",
    features: ["Stainless steel", "Corrosion resistant", "Durable", "Heavy-duty", "Environmental resistant"],
    applications: ["Coastal work", "Chemical environments", "Harsh conditions", "Long-term use"],
  },
  {
    id: "fp-013",
    name: "I UB 2011",
    category: "fall-protection",
    subcategory: "Harness Accessories",
    brand: "Irudek",
    description: "Universal harness accessory component for multiple fall protection configurations",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/i-ub-2011.jpg",
    features: ["Universal fit", "Multiple applications", "Durable construction", "Easy installation", "Compatible"],
    applications: ["Various harness systems", "Fall protection setup", "Multi-purpose use", "Industrial applications"],
  },
  {
    id: "fp-014",
    name: "I UB 2011S",
    category: "fall-protection",
    subcategory: "Harness Accessories",
    brand: "Irudek",
    description: "Specialized version of UB 2011 with enhanced safety features and durability",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/i-ub-2011s.jpg",
    features: ["Enhanced safety", "Specialist design", "Heavy-duty material", "Reinforced construction", "Premium quality"],
    applications: ["High-risk environments", "Professional use", "Demanding conditions", "Safety-critical applications"],
  },
  {
    id: "fp-015",
    name: "I UB 2020",
    category: "fall-protection",
    subcategory: "Harness Accessories",
    brand: "Irudek",
    description: "Advanced harness accessory providing superior connection and load distribution",
    image: "https://udyogisafety.com/wp-content/uploads/2024/03/i-ub-2020.jpg",
    features: ["Advanced design", "Superior connection", "Load distribution", "Heavy-duty rated", "Professional-grade"],
    applications: ["Complex rigging", "Heavy loads", "Professional operations", "Industrial height work"],
  },
]
