import type { Product } from "../types"

export const footProtectionProducts: Product[] = [
  {
    id: "foot-001",
    name: "Hillson Edge Active Safety Shoes",
    category: "foot-protection",
    subcategory: "Safety Shoes",
    brand: "Hillson",
    description: "Sporty design safety shoes with steel toe cap for industrial use",
    image: "/images/products/hillson-edge-active.jpg",
    features: ["Steel toe cap", "Sporty design", "Comfortable fit", "Anti-slip sole", "Lightweight"],
    applications: ["Manufacturing", "Warehousing", "General industry", "Logistics"],
  },
  {
    id: "foot-002",
    name: "Hillson Edge Trek Safety Shoes",
    category: "foot-protection",
    subcategory: "Safety Shoes",
    brand: "Hillson",
    description: "Rugged trekking style safety shoes for outdoor and industrial work",
    image: "/images/products/hillson-edge-trek.jpg",
    features: ["Steel toe protection", "Trekking design", "Durable construction", "Good grip", "Comfortable"],
    applications: ["Construction", "Outdoor work", "Heavy industry", "Field work"],
  },
  {
    id: "foot-003",
    name: "Hillson Edge Hike Safety Shoes",
    category: "foot-protection",
    subcategory: "Safety Shoes",
    brand: "Hillson",
    description: "Hiking boot style safety shoes with ankle support",
    image: "/images/products/hillson-edge-hike.jpg",
    features: ["Ankle support", "Steel toe cap", "Hiking boot style", "Comfortable fit", "Durable"],
    applications: ["Construction", "Mining", "Heavy-duty work", "Outdoor environments"],
  },
  {
    id: "foot-004",
    name: "Hillson Beston Safety Shoes",
    category: "foot-protection",
    subcategory: "Safety Shoes",
    brand: "Hillson",
    description: "Classic design safety shoes for everyday industrial use",
    image: "/images/products/hillson-beston.jpg",
    features: ["Steel toe protection", "Classic design", "Durable leather", "Comfortable", "Cost-effective"],
    applications: ["General industry", "Manufacturing", "Warehousing", "Daily use"],
  },
  {
    id: "foot-005",
    name: "Hillson Armour Safety Shoes",
    category: "foot-protection",
    subcategory: "Safety Shoes",
    brand: "Hillson",
    description: "Heavy-duty safety shoes with reinforced protection",
    image: "/images/products/hillson-armour.jpg",
    features: ["Reinforced toe cap", "Heavy-duty construction", "Slip-resistant", "Durable", "Professional grade"],
    applications: ["Heavy industry", "Construction", "Mining", "Metal fabrication"],
  },
  {
    id: "foot-006",
    name: "Hillson Nucleus Safety Shoes",
    category: "foot-protection",
    subcategory: "Safety Shoes",
    brand: "Hillson",
    description: "Modern design safety shoes with advanced comfort features",
    image: "/images/products/hillson-nucleus.jpg",
    features: ["Modern design", "Steel toe cap", "Cushioned insole", "Breathable", "Lightweight"],
    applications: ["Manufacturing", "Logistics", "Retail", "Light industry"],
  },
  {
    id: "foot-007",
    name: "Hillson Z+ Safety Shoes",
    category: "foot-protection",
    subcategory: "Safety Shoes",
    brand: "Hillson",
    description: "Premium safety shoes with extra comfort and protection",
    image: "/images/products/hillson-z-plus.jpg",
    features: ["Premium quality", "Enhanced comfort", "Steel toe protection", "Stylish design", "Durable"],
    applications: ["Professional use", "Manufacturing", "General industry", "Supervisory roles"],
  },
  {
    id: "foot-008",
    name: "Hillson Jungle King Gumboots",
    category: "foot-protection",
    subcategory: "Gumboots",
    brand: "Hillson",
    description: "Heavy-duty rubber gumboots for wet and muddy conditions",
    image: "/images/products/hillson-jungle-king.jpg",
    features: ["100% rubber", "Waterproof", "Steel toe cap", "Deep tread pattern", "Durable"],
    applications: ["Agriculture", "Mining", "Wet environments", "Chemical plants"],
  },
  {
    id: "foot-009",
    name: "Hillson Don Gumboots",
    category: "foot-protection",
    subcategory: "Gumboots",
    brand: "Hillson",
    description: "Professional gumboots with steel toe for industrial use",
    image: "/images/products/hillson-don.jpg",
    features: ["Steel toe protection", "Waterproof", "Chemical resistant", "Good grip", "Comfortable fit"],
    applications: ["Chemical industry", "Food processing", "Cleaning", "Wet work"],
  },
  {
    id: "foot-010",
    name: "Hillson Welsafe Gumboots",
    category: "foot-protection",
    subcategory: "Gumboots",
    brand: "Hillson",
    description: "Welding rated gumboots with heat and spark resistance",
    image: "/images/products/hillson-welsafe.jpg",
    features: ["Welding rated", "Heat resistant", "Spark resistant", "Steel toe cap", "Durable rubber"],
    applications: ["Welding", "Foundries", "Metal work", "Hot environments"],
  },
  {
    id: "foot-011",
    name: "Hillson Chemsafe Gumboots",
    category: "foot-protection",
    subcategory: "Gumboots",
    brand: "Hillson",
    description: "Chemical resistant gumboots for hazardous environments",
    image: "/images/products/hillson-chemsafe.jpg",
    features: ["Chemical resistant", "Acid resistant", "Steel toe protection", "Waterproof", "Durable"],
    applications: ["Chemical plants", "Laboratories", "Acid handling", "Hazardous materials"],
  },
  {
    id: "foot-012",
    name: "PVC Safety Gumboots",
    category: "foot-protection",
    subcategory: "Gumboots",
    brand: "Udyogi Safety",
    description: "Standard PVC gumboots for general wet work",
    image: "/images/products/pvc-gumboots.jpg",
    features: ["PVC construction", "Waterproof", "Cost-effective", "Good grip", "Durable"],
    applications: ["Agriculture", "Cleaning", "Wet work", "General use"],
  },
  {
    id: "foot-013",
    name: "Nitrile Gumboots",
    category: "foot-protection",
    subcategory: "Gumboots",
    brand: "Udyogi Safety",
    description: "Nitrile rubber gumboots with superior chemical resistance",
    image: "/images/products/nitrile-gumboots.jpg",
    features: ["Nitrile rubber", "Excellent chemical resistance", "Oil resistant", "Steel toe cap", "Durable"],
    applications: ["Oil industry", "Chemical plants", "Petrochemical", "Refineries"],
  },
  {
    id: "foot-014",
    name: "White Gumboots",
    category: "foot-protection",
    subcategory: "Gumboots",
    brand: "Udyogi Safety",
    description: "White gumboots for food and pharmaceutical industries",
    image: "/images/products/white-gumboots.jpg",
    features: ["Food safe", "White color", "Steel toe cap", "Easy to clean", "Waterproof"],
    applications: ["Food processing", "Pharmaceutical", "Dairy", "Clean rooms"],
  },
  {
    id: "foot-015",
    name: "Ankle Length Gumboots",
    category: "foot-protection",
    subcategory: "Gumboots",
    brand: "Udyogi Safety",
    description: "Short ankle gumboots for light wet work",
    image: "/images/products/ankle-gumboots.jpg",
    features: ["Ankle length", "Lightweight", "Waterproof", "Easy to wear", "Comfortable"],
    applications: ["Light wet work", "Car washing", "Gardening", "Light industry"],
  },
  {
    id: "foot-016",
    name: "Thigh Length Gumboots",
    category: "foot-protection",
    subcategory: "Gumboots",
    brand: "Udyogi Safety",
    description: "Extra-long thigh high gumboots for deep water work",
    image: "/images/products/thigh-gumboots.jpg",
    features: ["Thigh high", "Maximum protection", "Waterproof", "Steel toe cap", "Heavy-duty"],
    applications: ["Deep water work", "Sewage", "Flood response", "Tank cleaning"],
  },
  {
    id: "foot-017",
    name: "Steel Toe Inserts",
    category: "foot-protection",
    subcategory: "Accessories",
    brand: "Udyogi Safety",
    description: "Replacement steel toe cap inserts for safety shoes",
    image: "/images/products/steel-toe-insert.jpg",
    features: ["Steel construction", "Impact protection", "Standard size", "Easy installation", "Durable"],
    applications: ["Shoe repair", "Replacement parts", "Custom safety shoes", "Maintenance"],
  },
  {
    id: "foot-018",
    name: "Safety Shoe Insoles",
    category: "foot-protection",
    subcategory: "Accessories",
    brand: "Udyogi Safety",
    description: "Cushioned insoles for enhanced comfort in safety shoes",
    image: "/images/products/safety-insoles.jpg",
    features: ["Cushioned comfort", "Arch support", "Moisture wicking", "Anti-odor", "Replaceable"],
    applications: ["All safety shoes", "Extended wear", "Comfort enhancement", "General use"],
  },
  {
    id: "foot-019",
    name: "Metatarsal Guards",
    category: "foot-protection",
    subcategory: "Accessories",
    brand: "Udyogi Safety",
    description: "External metatarsal guards for additional foot protection",
    image: "/images/products/metatarsal-guards.jpg",
    features: ["Metatarsal protection", "Strap-on design", "Impact resistant", "Adjustable", "Durable"],
    applications: ["Heavy industry", "Metal work", "Construction", "Additional protection"],
  },
  {
    id: "foot-020",
    name: "Anti-Slip Shoe Covers",
    category: "foot-protection",
    subcategory: "Accessories",
    brand: "Udyogi Safety",
    description: "Disposable shoe covers with anti-slip sole",
    image: "/images/products/shoe-covers.jpg",
    features: ["Disposable", "Anti-slip sole", "Universal fit", "Water resistant", "Economical"],
    applications: ["Clean rooms", "Food industry", "Hospitals", "Visitor areas"],
  },
  {
    id: "foot-021",
    name: "Shoe Spikes for Ice",
    category: "foot-protection",
    subcategory: "Accessories",
    brand: "Udyogi Safety",
    description: "Attachable ice spikes for traction on snow and ice",
    image: "/images/products/ice-spikes.jpg",
    features: ["Ice traction", "Easy attachment", "Durable spikes", "Universal fit", "Portable"],
    applications: ["Winter work", "Cold storage", "Icy conditions", "Outdoor winter work"],
  },
  {
    id: "foot-022",
    name: "Electrical Hazard Boots",
    category: "foot-protection",
    subcategory: "Safety Shoes",
    brand: "Udyogi Safety",
    description: "EH rated safety boots for electrical work",
    image: "/images/products/eh-boots.jpg",
    features: ["Electrical hazard rated", "Steel toe cap", "Non-conductive sole", "Durable", "Professional grade"],
    applications: ["Electrical work", "High voltage areas", "Utilities", "Electrical contractors"],
  },
  {
    id: "foot-023",
    name: "Conductive Safety Shoes",
    category: "foot-protection",
    subcategory: "Safety Shoes",
    brand: "Udyogi Safety",
    description: "ESD/anti-static safety shoes for static-sensitive work",
    image: "/images/products/conductive-shoes.jpg",
    features: ["ESD safe", "Anti-static", "Steel toe protection", "Comfortable", "Clean room compatible"],
    applications: ["Electronics manufacturing", "Clean rooms", "Static-sensitive areas", "Semiconductor"],
  },
  {
    id: "foot-024",
    name: "Foundry Boots",
    category: "foot-protection",
    subcategory: "Safety Shoes",
    brand: "Udyogi Safety",
    description: "Heat resistant boots for foundry and metal work",
    image: "/images/products/foundry-boots.jpg",
    features: ["Heat resistant", "Metatarsal protection", "Spark resistant", "Steel toe cap", "Heavy-duty"],
    applications: ["Foundries", "Metal casting", "Welding", "Hot metal work"],
  },
  {
    id: "foot-025",
    name: "Logger Boots",
    category: "foot-protection",
    subcategory: "Safety Shoes",
    brand: "Udyogi Safety",
    description: "High ankle boots with chainsaw protection",
    image: "/images/products/logger-boots.jpg",
    features: ["Chainsaw protection", "High ankle support", "Steel toe cap", "Waterproof", "Aggressive tread"],
    applications: ["Forestry", "Logging", "Chainsaw work", "Outdoor heavy work"],
  },
  {
    id: "foot-026",
    name: "Waterproof Safety Boots",
    category: "foot-protection",
    subcategory: "Safety Shoes",
    brand: "Udyogi Safety",
    description: "Waterproof leather safety boots for wet conditions",
    image: "/images/products/waterproof-boots.jpg",
    features: ["Waterproof leather", "Steel toe cap", "Breathable membrane", "Comfortable", "Durable"],
    applications: ["Outdoor construction", "Wet environments", "All-weather work", "Field operations"],
  },
  {
    id: "foot-027",
    name: "Composite Toe Safety Shoes",
    category: "foot-protection",
    subcategory: "Safety Shoes",
    brand: "Udyogi Safety",
    description: "Non-metallic composite toe safety shoes for airport and security use",
    image: "/images/products/composite-toe.jpg",
    features: ["Composite toe cap", "Metal-free", "Lightweight", "Airport friendly", "Comfortable"],
    applications: ["Airport security", "Metal detection areas", "Electronics", "Light industry"],
  },
]
