import type { Product } from "../types"

export const harnessProducts: Product[] = [
  {
    id: "har-001",
    name: "VAYU YU01 Full Body Harness",
    category: "harness",
    subcategory: "Professional Grade Harnesses",
    brand: "Udyogi Safety",
    description:
      "Premium professional-grade full body harness with advanced comfort padding and multiple D-rings for versatile fall protection applications",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/191202-027-VAYU.jpg",
    features: [
      "Premium padded shoulder straps for all-day comfort",
      "Multiple attachment points (dorsal, sternal, lateral)",
      "Quick-connect buckle system for easy donning",
      "Heavy-duty webbing with reinforced stitching",
      "Complies with EN 361 and IS 3521 standards",
    ],
    applications: [
      "Construction and building work",
      "Telecom tower climbing",
      "Wind turbine maintenance",
      "Industrial maintenance",
      "Fall arrest systems",
    ],
  },
  {
    id: "har-002",
    name: "ULTRATEK Full Body Harness",
    category: "harness",
    subcategory: "Professional Grade Harnesses",
    brand: "Udyogi Safety",
    description:
      "Ultra-lightweight yet robust full body harness designed for maximum mobility and comfort during extended use",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/Ultratek.jpg",
    features: [
      "Lightweight construction reduces fatigue",
      "Breathable padding for hot environments",
      "One dorsal and two sternal D-rings",
      "Quick-adjust leg and chest straps",
      "Reflective strips for visibility",
    ],
    applications: [
      "Scaffolding work",
      "Confined space entry",
      "Roofing applications",
      "Steel erection",
      "General fall protection",
    ],
  },
  {
    id: "har-003",
    name: "TRIVAGO Full Body Harness",
    category: "harness",
    subcategory: "Professional Grade Harnesses",
    brand: "Udyogi Safety",
    description:
      "Three-point adjustment full body harness offering excellent weight distribution and comfort for industrial applications",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/191202-024-Trivago.jpg",
    features: [
      "Three-point adjustment system",
      "Padded waist belt for load distribution",
      "Corrosion-resistant hardware",
      "Color-coded adjustment points",
      "Meets international safety standards",
    ],
    applications: [
      "Industrial maintenance",
      "Construction sites",
      "Warehouse operations",
      "Utility work",
      "Emergency rescue",
    ],
  },
  {
    id: "har-004",
    name: "ECO 1 Full Body Harness",
    category: "harness",
    subcategory: "Economical Harnesses",
    brand: "Udyogi Safety",
    description: "Cost-effective full body harness providing essential fall protection for light-duty applications",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/210514-001-ECO-1.jpg",
    features: [
      "Economical design without compromising safety",
      "Single dorsal D-ring attachment",
      "Adjustable leg and chest straps",
      "Lightweight polyester webbing",
      "Easy to use and maintain",
    ],
    applications: [
      "Light construction work",
      "Basic fall protection",
      "Maintenance tasks",
      "Short-duration work",
      "Training purposes",
    ],
  },
  {
    id: "har-005",
    name: "ECO 2 Full Body Harness",
    category: "harness",
    subcategory: "Economical Harnesses",
    brand: "Udyogi Safety",
    description: "Enhanced economical harness with improved padding and adjustment features",
    image: "https://udyogisafety.com/wp-content/uploads/2023/06/ECO-2.jpg",
    features: [
      "Improved padding over ECO 1",
      "Quick-release buckles",
      "Durable webbing construction",
      "Standard compliant",
      "Color-coded straps",
    ],
    applications: [
      "General industrial use",
      "Facility maintenance",
      "Basic height work",
      "Equipment installation",
      "Light-duty fall arrest",
    ],
  },
  {
    id: "har-006",
    name: "ECO 3 Full Body Harness",
    category: "harness",
    subcategory: "Economical Harnesses",
    brand: "Udyogi Safety",
    description: "Mid-range economical harness offering good comfort and protection balance",
    image: "https://udyogisafety.com/wp-content/uploads/2023/06/ECO-3.jpg",
    features: [
      "Balanced comfort and economy",
      "Reinforced stitching at critical points",
      "Easy-adjust shoulder straps",
      "Standard-compliant hardware",
      "Suitable for regular use",
    ],
    applications: [
      "Regular industrial maintenance",
      "Construction work",
      "Utility operations",
      "Building services",
      "General fall protection",
    ],
  },
  {
    id: "har-007",
    name: "ECO 4 Full Body Harness",
    category: "harness",
    subcategory: "Economical Harnesses",
    brand: "Udyogi Safety",
    description: "Advanced economical model with premium features at an affordable price",
    image: "https://udyogisafety.com/wp-content/uploads/2023/06/ECO-4.jpg",
    features: [
      "Premium features at economical price",
      "Enhanced padding for comfort",
      "Multiple size adjustments",
      "Durable construction",
      "High-quality buckles",
    ],
    applications: [
      "Extended duration work",
      "Industrial applications",
      "Construction projects",
      "Maintenance operations",
      "Professional use",
    ],
  },
  {
    id: "har-008",
    name: "ECO 1/KG Full Body Harness with Vest",
    category: "harness",
    subcategory: "High Visibility Vest Harnesses",
    brand: "Udyogi Safety",
    description:
      "High-visibility lime green vest-style harness combining fall protection with enhanced visibility for maximum safety",
    image: "https://udyogisafety.com/wp-content/uploads/2023/06/ECO-1KG.jpg",
    features: [
      "Integrated high-visibility lime green vest",
      "Reflective strips for 360-degree visibility",
      "Comfortable vest construction",
      "Full body fall protection",
      "Meets visibility standards",
    ],
    applications: [
      "Road construction work",
      "Traffic management",
      "Low-light environments",
      "Highway maintenance",
      "Outdoor construction",
    ],
  },
  {
    id: "har-009",
    name: "ECO 1/KO Full Body Harness with Vest",
    category: "harness",
    subcategory: "High Visibility Vest Harnesses",
    brand: "Udyogi Safety",
    description: "High-visibility orange vest-style harness for maximum visibility in demanding work environments",
    image: "https://udyogisafety.com/wp-content/uploads/2023/06/ECO-1KO.jpg",
    features: [
      "Integrated high-visibility orange vest",
      "Wide reflective strips",
      "Breathable vest material",
      "Full harness protection",
      "Complies with visibility standards",
    ],
    applications: [
      "Highway construction",
      "Traffic control",
      "Emergency services",
      "Railway maintenance",
      "Airport operations",
    ],
  },
  {
    id: "har-010",
    name: "UB102 Full Body Harness",
    category: "harness",
    subcategory: "Standard Industrial Harnesses",
    brand: "Udyogi Safety",
    description: "Reliable standard industrial harness designed for everyday use in various work environments",
    image: "https://udyogisafety.com/wp-content/uploads/2023/06/UB102.jpg",
    features: [
      "Robust industrial-grade construction",
      "Single dorsal D-ring",
      "Adjustable leg loops",
      "Durable polyester webbing",
      "Standard-compliant design",
    ],
    applications: [
      "General industrial work",
      "Manufacturing facilities",
      "Warehousing",
      "Maintenance operations",
      "Construction sites",
    ],
  },
  {
    id: "har-011",
    name: "UB103 Full Body Harness",
    category: "harness",
    subcategory: "Standard Industrial Harnesses",
    brand: "Udyogi Safety",
    description: "Enhanced industrial harness with sit-strap for prolonged suspension comfort",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/210925-029-UB-103.jpg",
    features: [
      "Ideally positioned sit-strap for extended comfort",
      "Premium webbing material",
      "Reinforced attachment points",
      "Quick-adjust buckles",
      "Suitable for long-duration work",
    ],
    applications: [
      "Suspended access work",
      "Prolonged work at height",
      "Inspection tasks",
      "Painting operations",
      "Window cleaning",
    ],
  },
  {
    id: "har-012",
    name: "UB104 Full Body Harness",
    category: "harness",
    subcategory: "Standard Industrial Harnesses",
    brand: "Udyogi Safety",
    description: "Four-point adjustment harness for customizable fit and comfort",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/UB-104-4-POINT-HARNESS.jpg",
    features: [
      "Four-point adjustment system",
      "Customizable fit for all body types",
      "Heavy-duty D-ring",
      "Padded shoulder straps",
      "Industrial-strength construction",
    ],
    applications: [
      "Industrial maintenance",
      "Construction work",
      "Utility operations",
      "Telecom work",
      "General height safety",
    ],
  },
  {
    id: "har-013",
    name: "UB121 Full Body Harness",
    category: "harness",
    subcategory: "Standard Industrial Harnesses",
    brand: "Udyogi Safety",
    description: "Advanced industrial harness with multiple attachment points for versatile applications",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/UB-121-1.jpg",
    features: [
      "Multiple D-ring attachment points",
      "Versatile configuration options",
      "Premium quality webbing",
      "Corrosion-resistant hardware",
      "Ergonomic design",
    ],
    applications: [
      "Complex work positioning",
      "Industrial rescue",
      "Confined space work",
      "Advanced fall protection",
      "Multi-point anchorage",
    ],
  },
  {
    id: "har-014",
    name: "Tango II Full Body Harness",
    category: "harness",
    subcategory: "Comfort Plus Harnesses",
    brand: "Udyogi Safety",
    description: "Premium comfort harness with advanced padding and ergonomic design for all-day wear",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/Tango-II.jpg",
    features: [
      "Advanced comfort padding system",
      "Ergonomic weight distribution",
      "Premium quality materials",
      "Multiple adjustment points",
      "Breathable construction",
    ],
    applications: [
      "Extended duration work",
      "Professional applications",
      "Premium construction projects",
      "High-end industrial facilities",
      "Comfort-critical operations",
    ],
  },
  {
    id: "har-015",
    name: "UB102 Plus Full Body Harness",
    category: "harness",
    subcategory: "Comfort Plus Harnesses",
    brand: "Udyogi Safety",
    description: "Enhanced version of UB102 with additional padding and comfort features",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/210925-029-UB-102-Plus-1.jpg",
    features: [
      "Enhanced padding over standard UB102",
      "Improved comfort for long wear",
      "Additional adjustment points",
      "Premium buckle system",
      "Superior weight distribution",
    ],
    applications: [
      "Long-duration industrial work",
      "Professional construction",
      "Extended maintenance tasks",
      "Comfort-required applications",
      "Premium project work",
    ],
  },
  {
    id: "har-016",
    name: "UB103 Plus Full Body Harness",
    category: "harness",
    subcategory: "Comfort Plus Harnesses",
    brand: "Udyogi Safety",
    description: "Premium version of UB103 with enhanced sit-strap and comfort padding",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/UB-103-Plus.jpg",
    features: [
      "Enhanced sit-strap with extra padding",
      "Premium comfort construction",
      "Advanced adjustment system",
      "High-quality materials",
      "Optimal for suspended work",
    ],
    applications: [
      "Extended suspended access",
      "Premium inspection work",
      "Long-duration painting",
      "Professional window cleaning",
      "Comfort-critical suspended tasks",
    ],
  },
  {
    id: "har-017",
    name: "UB102 FR Full Body Harness",
    category: "harness",
    subcategory: "Flame Resistant Harnesses",
    brand: "Udyogi Safety",
    description: "Flame-resistant full body harness for hot work and welding applications",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/UB-102-FR.jpg",
    features: [
      "Flame-resistant webbing material",
      "Heat-resistant hardware",
      "Suitable for welding environments",
      "Maintains strength in heat exposure",
      "Complies with flame resistance standards",
    ],
    applications: [
      "Welding at heights",
      "Hot work operations",
      "Steel fabrication",
      "Foundry work",
      "High-temperature environments",
    ],
  },
  {
    id: "har-018",
    name: "VIDYUT UB102 DE Full Body Harness",
    category: "harness",
    subcategory: "Electrical Safety Harnesses",
    brand: "Udyogi Safety",
    description: "Electrically insulated full body harness designed for electrical work and live line applications",
    image: "https://udyogisafety.com/wp-content/uploads/2021/12/VIDYUT-UB102DE.jpg",
    features: [
      "Dielectric (non-conductive) webbing",
      "Insulated hardware components",
      "Suitable for electrical environments",
      "Prevents electrical conductivity",
      "Meets electrical safety standards",
    ],
    applications: [
      "Electrical maintenance",
      "Power line work",
      "Substation operations",
      "Live electrical work",
      "Utility electrical tasks",
    ],
  },
  {
    id: "har-019",
    name: "VIDYUT ULTRATEK DE Full Body Harness",
    category: "harness",
    subcategory: "Electrical Safety Harnesses",
    brand: "Udyogi Safety",
    description: "Premium electrically insulated harness with advanced features for electrical safety",
    image: "https://udyogisafety.com/wp-content/uploads/2021/12/VIDYUT-ULTRATEK-DE.jpg",
    features: [
      "Premium dielectric construction",
      "Advanced insulation technology",
      "Lightweight yet robust",
      "Enhanced electrical protection",
      "Professional-grade design",
    ],
    applications: [
      "High-voltage work",
      "Electrical installation",
      "Power transmission work",
      "Critical electrical operations",
      "Professional electrical tasks",
    ],
  },
  {
    id: "har-020",
    name: "UB102 AS Lite Full Body Harness",
    category: "harness",
    subcategory: "Arc Flash Harnesses",
    brand: "Udyogi Safety",
    description: "Arc flash rated harness with anti-static properties for electrical hazard protection",
    image: "https://udyogisafety.com/wp-content/uploads/2021/12/UB-102-AS-Lite.jpg",
    features: [
      "Arc flash protection rating",
      "Anti-static webbing material",
      "Lightweight design",
      "Electrical hazard protection",
      "Static dissipative properties",
    ],
    applications: [
      "Arc flash environments",
      "Electrical panel work",
      "Switch gear operations",
      "Electrical testing",
      "High-risk electrical tasks",
    ],
  },
  {
    id: "har-021",
    name: "ULTRATEK AS Full Body Harness",
    category: "harness",
    subcategory: "Arc Flash Harnesses",
    brand: "Udyogi Safety",
    description: "Premium arc flash and anti-static harness for advanced electrical safety",
    image: "https://udyogisafety.com/wp-content/uploads/2021/12/200630-035-Ultratek-AS-2048x2048.jpg",
    features: [
      "Advanced arc flash protection",
      "Anti-static construction",
      "Premium electrical safety features",
      "Lightweight and comfortable",
      "Professional electrical-grade",
    ],
    applications: [
      "Advanced electrical work",
      "Arc flash rated areas",
      "Critical electrical operations",
      "Professional electrical tasks",
      "High-hazard electrical environments",
    ],
  },
  {
    id: "har-022",
    name: "ULTRA-01 Full Body Harness",
    category: "harness",
    subcategory: "Premium Leather Harnesses",
    brand: "Udyogi Safety",
    description: "Premium leather full body harness for heavy-duty industrial applications",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/ULTRA-01.jpg",
    features: [
      "High-quality leather construction",
      "Exceptional durability",
      "Premium hardware",
      "Professional-grade design",
      "Long service life",
    ],
    applications: [
      "Heavy industrial work",
      "Professional construction",
      "Demanding environments",
      "Premium applications",
      "Long-term intensive use",
    ],
  },
  {
    id: "har-023",
    name: "ULTRA-02 Full Body Harness",
    category: "harness",
    subcategory: "Premium Leather Harnesses",
    brand: "Udyogi Safety",
    description: "Advanced leather harness with enhanced features and comfort",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/ULTRA-02.jpg",
    features: [
      "Premium leather with comfort padding",
      "Advanced adjustment system",
      "Heavy-duty construction",
      "Superior quality hardware",
      "Professional-grade materials",
    ],
    applications: [
      "Premium construction projects",
      "Professional industrial work",
      "High-quality applications",
      "Demanding work environments",
      "Long-duration heavy work",
    ],
  },
  {
    id: "har-024",
    name: "ULTRA-05 Full Body Harness",
    category: "harness",
    subcategory: "Premium Leather Harnesses",
    brand: "Udyogi Safety",
    description: "Top-tier leather harness with maximum comfort and durability features",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/ULTRA-05.jpg",
    features: [
      "Top-grade leather construction",
      "Maximum comfort padding",
      "Premium adjustment system",
      "Exceptional durability",
      "Professional quality",
    ],
    applications: [
      "Premium industrial applications",
      "Professional construction",
      "High-end projects",
      "Executive-level safety",
      "Comfort-critical heavy work",
    ],
  },
  {
    id: "har-025",
    name: "UK01 Lite Full Body Harness",
    category: "harness",
    subcategory: "Lightweight Harnesses",
    brand: "Udyogi Safety",
    description: "Ultra-lightweight harness designed for maximum mobility and comfort",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/UK01-Lite.jpg",
    features: [
      "Ultra-lightweight construction",
      "Maximum mobility",
      "Minimal bulk design",
      "Quick-don features",
      "Ideal for agile work",
    ],
    applications: [
      "Agile construction work",
      "Quick access tasks",
      "Mobile maintenance",
      "Rapid response work",
      "Lightweight-required applications",
    ],
  },
  {
    id: "har-026",
    name: "UK-04 Full Body Harness",
    category: "harness",
    subcategory: "Lightweight Harnesses",
    brand: "Udyogi Safety",
    description: "Lightweight harness with four-point adjustment for comfort and mobility",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/UK-04.jpg",
    features: [
      "Lightweight with adjustment features",
      "Four-point adjustment",
      "Comfortable for extended wear",
      "Agile design",
      "Quick-release buckles",
    ],
    applications: [
      "Mobile industrial work",
      "Agile construction",
      "Quick tasks at height",
      "Maintenance operations",
      "General lightweight applications",
    ],
  },
  {
    id: "har-027",
    name: "UK01 JKO Full Body Harness with Vest",
    category: "harness",
    subcategory: "High Visibility Vest Harnesses",
    brand: "Udyogi Safety",
    description: "Lightweight harness with integrated high-visibility orange vest for maximum visibility and comfort",
    image: "https://udyogisafety.com/wp-content/uploads/2023/06/UK01-JKO.jpg",
    features: [
      "Integrated high-visibility orange vest",
      "Lightweight construction",
      "Reflective strips for visibility",
      "Comfortable vest design",
      "Quick-don features",
    ],
    applications: [
      "Road construction",
      "Traffic management",
      "Highway maintenance",
      "Low-light work",
      "Outdoor construction",
    ],
  },
  {
    id: "har-028",
    name: "UK01 JKG Full Body Harness with Vest",
    category: "harness",
    subcategory: "High Visibility Vest Harnesses",
    brand: "Udyogi Safety",
    description: "Lightweight harness with integrated high-visibility lime green vest for enhanced safety and comfort",
    image: "https://udyogisafety.com/wp-content/uploads/2023/06/UK01-JKG.jpg",
    features: [
      "Integrated high-visibility lime green vest",
      "Lightweight and comfortable",
      "360-degree reflective strips",
      "Quick-adjust system",
      "Breathable vest material",
    ],
    applications: ["Road work", "Traffic control", "Railway maintenance", "Airport operations", "Emergency services"],
  },
  {
    id: "har-029",
    name: "PL01 Coiled Positioning Lanyard",
    category: "harness",
    subcategory: "Work Positioning Harnesses",
    brand: "Udyogi Safety",
    description: "Coiled work positioning lanyard for hands-free work at height with fall restraint",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/PL01.jpg",
    features: [
      "Coiled design prevents snagging",
      "Work positioning capability",
      "Hands-free operation",
      "Adjustable length",
      "Durable construction",
    ],
    applications: [
      "Hands-free work at height",
      "Pole climbing",
      "Tower work",
      "Utility operations",
      "Work positioning tasks",
    ],
  },
]
