import type { Product } from "../types"

export const headProtectionProducts: Product[] = [
  {
    id: "hp-001",
    name: "Thermoguard Safety Helmet",
    category: "head-protection",
    subcategory: "Thermoguard Series",
    brand: "Udyogi Safety",
    description: "High-temperature resistant safety helmet for industrial environments",
    image: "https://udyogisafety.com/wp-content/uploads/2023/06/thermoground-9000-serieis.jpg",
    features: [
      "Heat resistant up to 150°C",
      "Adjustable headband",
      "UV stabilized shell",
      "Complies with IS standards",
    ],
    applications: ["Steel plants", "Foundries", "Hot work areas", "Welding zones"],
  },
  {
    id: "hp-002",
    name: "Vista Safety Helmet",
    category: "head-protection",
    subcategory: "Vista Series",
    brand: "Udyogi Safety",
    description: "Premium visibility safety helmet with ventilation",
    image: "https://udyogisafety.com/wp-content/uploads/2020/01/Vista.jpg",
    features: ["High visibility colors", "Ventilation system", "Comfortable padding", "Ratchet adjustment"],
    applications: ["Construction sites", "Mining", "General industry", "Warehouses"],
  },
  {
    id: "hp-003",
    name: "Ultravent Safety Helmet",
    category: "head-protection",
    subcategory: "Ultravent Series",
    brand: "Udyogi Safety",
    description: "Ultra-ventilated helmet for hot and humid conditions",
    image: "https://udyogisafety.com/wp-content/uploads/2024/01/Ultravent-7000.jpg",
    features: ["Maximum ventilation", "Lightweight design", "Sweatband included", "High impact resistance"],
    applications: ["Hot environments", "Outdoor work", "Summer conditions", "Tropical climates"],
  },
  {
    id: "hp-004",
    name: "Fusion Safety Helmet",
    category: "head-protection",
    subcategory: "Fusion Series",
    brand: "Udyogi Safety",
    description: "Modern ergonomic design with superior protection",
    image: "https://udyogisafety.com/wp-content/uploads/2020/02/200704-087-Fusion-Without-Belt-2048x2048.jpg",
    features: ["Ergonomic fit", "Integrated accessory slots", "Durable ABS shell", "Color options available"],
    applications: ["Manufacturing", "Logistics", "Construction", "Industrial facilities"],
  },
  {
    id: "hp-005",
    name: "Electra Safety Helmet",
    category: "head-protection",
    subcategory: "Electra Series",
    brand: "Udyogi Safety",
    description: "Electrical safety helmet for high voltage work",
    image: "https://udyogisafety.com/wp-content/uploads/2023/12/ELECTRA.jpg",
    features: ["Dielectric protection", "Class E rated", "Non-conductive shell", "Electrical safety certified"],
    applications: ["Electrical work", "Power plants", "Substations", "Utility maintenance"],
  },
  {
    id: "hp-006",
    name: "UltraTuff Safety Helmet",
    category: "head-protection",
    subcategory: "UltraTuff Series",
    brand: "Udyogi Safety",
    description: "Ultra-tough helmet for heavy-duty industrial applications",
    image: "https://udyogisafety.com/wp-content/uploads/2023/08/ULTRA-TUFF-2000.jpg",
    features: ["Extra tough ABS shell", "Heavy-duty suspension", "Impact resistant", "Long-lasting durability"],
    applications: ["Heavy industry", "Mining", "Demolition", "Construction"],
  },
  {
    id: "hp-007",
    name: "Bump Cap - Blue",
    category: "head-protection",
    subcategory: "Bump Caps",
    brand: "Udyogi Safety",
    description: "Lightweight bump cap for low-risk environments",
    image: "https://udyogisafety.com/wp-content/uploads/2020/06/200702-040-Bump-Cap-Blue-2048x2048.jpg",
    features: ["Lightweight design", "Baseball cap style", "Minor bump protection", "Comfortable wear"],
    applications: ["Warehouses", "Low ceiling areas", "Automotive", "Light industrial"],
  },
  {
    id: "hp-008",
    name: "Bump Cap - Green",
    category: "head-protection",
    subcategory: "Bump Caps",
    brand: "Udyogi Safety",
    description: "Green bump cap for identification and protection",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/200702-037-Bump-Cap-FLOROSCENT-2048x2048.jpg",
    features: ["Lightweight protection", "High visibility green", "Ventilated design", "Adjustable fit"],
    applications: ["Warehousing", "Food processing", "Packaging", "Logistics"],
  },
  {
    id: "hp-009",
    name: "Fusion Pro Safety Helmet",
    category: "head-protection",
    subcategory: "Fusion Series",
    brand: "Udyogi Safety",
    description: "Professional grade helmet with advanced features",
    image: "https://udyogisafety.com/wp-content/uploads/2023/06/fusion-pro-3.jpg",
    features: ["Pro-grade protection", "Advanced suspension", "Multiple accessory slots", "Premium finish"],
    applications: ["Professional contractors", "Site management", "Engineering", "Supervision"],
  },
  {
    id: "hp-010",
    name: "Lighton Safety Helmet",
    category: "head-protection",
    subcategory: "Lighton Series",
    brand: "Udyogi Safety",
    description: "Ultra-lightweight helmet for all-day comfort",
    image: "https://udyogisafety.com/wp-content/uploads/2023/12/LIGHTON-231003-147_P.jpg",
    features: ["Ultra-lightweight", "All-day comfort", "Sweat-resistant padding", "Compact design"],
    applications: ["Long duration work", "Inspection", "Light construction", "Maintenance"],
  },
  {
    id: "hp-011",
    name: "Lighton ES Safety Helmet",
    category: "head-protection",
    subcategory: "Lighton Series",
    brand: "Udyogi Safety",
    description: "Enhanced safety version of Lighton with extra features",
    image: "https://udyogisafety.com/wp-content/uploads/2020/05/200704-035-LightOn-ES-Without-Belt-2.jpg",
    features: ["Enhanced safety rating", "Lightweight design", "Superior ventilation", "Premium materials"],
    applications: ["Professional use", "Extended wear", "Multi-environment", "All industries"],
  },
  {
    id: "hp-012",
    name: "Lighton V Safety Helmet",
    category: "head-protection",
    subcategory: "Lighton Series",
    brand: "Udyogi Safety",
    description: "Ventilated version for maximum airflow",
    image: "https://udyogisafety.com/wp-content/uploads/2020/12/LightOn-V-%E2%80%93-Safety-Helmet.jpg",
    features: ["Maximum ventilation", "Lightweight", "Hot climate optimized", "Moisture wicking"],
    applications: ["Hot environments", "Outdoor construction", "Summer work", "Tropical regions"],
  },
  {
    id: "hp-013",
    name: "Ultra Pro Safety Helmet",
    category: "head-protection",
    subcategory: "Ultra Series",
    brand: "Udyogi Safety",
    description: "Professional ultra-protection helmet",
    image: "https://udyogisafety.com/wp-content/uploads/2023/08/200704-032-Ultra-Pro-3000-Without-Belt-copy.jpg",
    features: ["Ultra protection rating", "Professional design", "Advanced materials", "Certified safety"],
    applications: ["High-risk environments", "Heavy construction", "Industrial plants", "Critical operations"],
  },
  {
    id: "hp-014",
    name: "Proton Safety Helmet",
    category: "head-protection",
    subcategory: "Proton Series",
    brand: "Udyogi Safety",
    description: "Advanced protection with modern styling",
    image: "https://udyogisafety.com/wp-content/uploads/2023/08/proton.jpg",
    features: ["Modern design", "Advanced protection", "Comfortable fit", "Durable construction"],
    applications: ["Modern facilities", "Tech industries", "Manufacturing", "Assembly"],
  },
  {
    id: "hp-015",
    name: "Prithvi Safety Helmet",
    category: "head-protection",
    subcategory: "Prithvi Series",
    brand: "Udyogi Safety",
    description: "Reliable protection for general industrial use",
    image: "https://udyogisafety.com/wp-content/uploads/2023/03/PRITHVI.jpg",
    features: ["Reliable protection", "Cost-effective", "IS certified", "Standard fit"],
    applications: ["General industry", "Manufacturing", "Construction", "Daily use"],
  },
  {
    id: "hp-016",
    name: "Ultra Safety Helmet",
    category: "head-protection",
    subcategory: "Ultra Series",
    brand: "Udyogi Safety",
    description: "Standard ultra-protection helmet for industrial use",
    image: "https://udyogisafety.com/wp-content/uploads/2020/01/Ultra-5000-Series-2.jpg",
    features: ["High impact resistance", "UV stabilized", "Comfortable suspension", "Multiple color options"],
    applications: ["Construction", "Manufacturing", "Industrial sites", "General protection"],
  },
  {
    id: "hp-017",
    name: "UI 1211 Safety Helmet",
    category: "head-protection",
    subcategory: "UI Series",
    brand: "Udyogi Safety",
    description: "Certified industrial helmet meeting international standards",
    image: "/images/products/ui-1211-helmet.jpg",
    features: [
      "IS & CE certified",
      "High visibility yellow",
      "Robust construction",
      "Tested to international standards",
    ],
    applications: ["Industrial plants", "Construction sites", "Manufacturing units", "Heavy industry"],
  },
]
