import type { Product } from "../types"

export const lanyardProducts: Product[] = [
  // Rope Lanyards
  {
    id: "lan-001",
    name: "RL22 Double Leg Rope Lanyard",
    category: "lanyard",
    subcategory: "Rope Lanyards",
    description: "Double leg rope lanyard with shock absorber for fall protection",
    price: 2800,
    image: "/images/products/rl22-rope-lanyard.jpg",
    featured: true,
    specifications: {
      material: "Nylon Rope",
      length: "1.8m",
      type: "Double Leg",
      connector: "Snap Hook",
      standard: "EN 355",
    },
    features: [
      "Integrated shock absorber",
      "Double leg design for 100% tie-off",
      "Durable nylon rope construction",
      "Corrosion-resistant hardware",
    ],
    applications: ["Construction work at height", "Tower climbing", "Industrial maintenance", "Scaffolding work"],
  },
  {
    id: "lan-002",
    name: "RL61 Single Leg Rope Lanyard",
    category: "lanyard",
    subcategory: "Rope Lanyards",
    description: "Single leg rope lanyard with shock absorber",
    price: 1800,
    image: "/images/products/rl61-rope-lanyard.jpg",
    specifications: {
      material: "Nylon Rope",
      length: "1.8m",
      type: "Single Leg",
      connector: "Snap Hook",
      standard: "EN 355",
    },
    features: ["Integrated shock absorber", "Lightweight design", "High strength rope", "Easy to use snap hooks"],
    applications: ["General work at height", "Maintenance work", "Confined space entry", "Temporary access"],
  },
  // Braided Lanyards
  {
    id: "lan-003",
    name: "BL22 Double Leg Braided Lanyard",
    category: "lanyard",
    subcategory: "Braided Lanyards",
    description: "Double leg braided lanyard with energy absorber",
    price: 3200,
    image: "/images/products/bl22-braided-lanyard.jpg",
    featured: true,
    specifications: {
      material: "Braided Polyester",
      length: "1.8m",
      type: "Double Leg",
      connector: "Scaffold Hook",
      standard: "EN 355",
    },
    features: [
      "High abrasion resistance",
      "Double leg for continuous protection",
      "Energy absorbing system",
      "UV resistant material",
    ],
    applications: ["Heavy duty construction", "Steel erection", "Bridge work", "Industrial applications"],
  },
  {
    id: "lan-004",
    name: "BL61 Single Leg Braided Lanyard",
    category: "lanyard",
    subcategory: "Braided Lanyards",
    description: "Single leg braided lanyard for fall protection",
    price: 2200,
    image: "/images/products/bl61-braided-lanyard.jpg",
    specifications: {
      material: "Braided Polyester",
      length: "1.8m",
      type: "Single Leg",
      connector: "Snap Hook",
      standard: "EN 355",
    },
    features: ["Durable braided construction", "Shock absorber included", "Weather resistant", "Compact design"],
    applications: ["Construction sites", "Wind turbine maintenance", "Roofing work", "General industrial use"],
  },
  {
    id: "lan-005",
    name: "BL80 Heavy Duty Braided Lanyard",
    category: "lanyard",
    subcategory: "Braided Lanyards",
    description: "Heavy duty single leg braided lanyard with 80kg capacity",
    price: 2600,
    image: "/images/products/bl80-braided-lanyard.jpg",
    specifications: {
      material: "Heavy Duty Braided Polyester",
      length: "2.0m",
      type: "Single Leg",
      connector: "Large Scaffold Hook",
      standard: "EN 355",
    },
    features: [
      "Increased capacity up to 80kg",
      "Extra strong construction",
      "Enhanced shock absorption",
      "Heavy duty connectors",
    ],
    applications: ["Heavy equipment work", "Industrial construction", "Mining operations", "Oil and gas industry"],
  },
  // Webbing Lanyards
  {
    id: "lan-006",
    name: "WL22 Double Leg Webbing Lanyard",
    category: "lanyard",
    subcategory: "Webbing Lanyards",
    description: "Double leg webbing lanyard with shock absorber",
    price: 2400,
    image: "/images/products/wl22-webbing-lanyard.jpg",
    featured: true,
    specifications: {
      material: "Polyester Webbing",
      length: "1.8m",
      type: "Double Leg",
      connector: "Snap Hook",
      standard: "EN 355",
    },
    features: [
      "Lightweight webbing design",
      "Easy to inspect for damage",
      "Double leg safety",
      "Compact energy absorber",
    ],
    applications: ["Telecommunication towers", "Building maintenance", "Window cleaning", "HVAC installation"],
  },
  // Elastic Lanyards
  {
    id: "lan-007",
    name: "EL22 Double Leg Elastic Lanyard",
    category: "lanyard",
    subcategory: "Elastic Lanyards",
    description: "Double leg elastic lanyard for extended reach",
    price: 3600,
    image: "/images/products/el22-elastic-lanyard.jpg",
    specifications: {
      material: "Elastic Webbing",
      length: "1.2m-1.8m (Expandable)",
      type: "Double Leg",
      connector: "Snap Hook",
      standard: "EN 355",
    },
    features: ["Expandable elastic design", "Reduced trip hazards", "Self-retracting feature", "Double leg protection"],
    applications: ["Mobile work platforms", "Ladder climbing", "Restricted work areas", "Manufacturing facilities"],
  },
  {
    id: "lan-008",
    name: "EL61 Single Leg Elastic Lanyard",
    category: "lanyard",
    subcategory: "Elastic Lanyards",
    description: "Single leg elastic lanyard with shock absorber",
    price: 2600,
    image: "/images/products/el61-elastic-lanyard.jpg",
    specifications: {
      material: "Elastic Webbing",
      length: "1.0m-1.6m (Expandable)",
      type: "Single Leg",
      connector: "Snap Hook",
      standard: "EN 355",
    },
    features: [
      "Compact when not extended",
      "Reduces tripping hazards",
      "Integrated shock absorber",
      "Lightweight design",
    ],
    applications: ["Warehouse work", "Assembly lines", "Confined spaces", "General maintenance"],
  },
  // Specialty Lanyards
  {
    id: "lan-009",
    name: "WL22 FR Flame Resistant Lanyard",
    category: "lanyard",
    subcategory: "Specialty Lanyards",
    description: "Flame resistant double leg webbing lanyard",
    price: 4200,
    image: "/images/products/wl22-fr-lanyard.jpg",
    specifications: {
      material: "Flame Resistant Webbing",
      length: "1.8m",
      type: "Double Leg",
      connector: "Steel Snap Hook",
      standard: "EN 355, Flame Resistant",
    },
    features: ["Flame resistant material", "Hot work approved", "Double leg safety", "Heat resistant connectors"],
    applications: ["Welding operations", "Hot work permits", "Foundry work", "Petrochemical plants"],
  },
  {
    id: "lan-010",
    name: "WL20AS Anti-Static Lanyard",
    category: "lanyard",
    subcategory: "Specialty Lanyards",
    description: "Anti-static webbing lanyard for ESD environments",
    price: 3800,
    image: "/images/products/wl20as-lanyard.jpg",
    specifications: {
      material: "Anti-Static Webbing",
      length: "2.0m",
      type: "Single Leg",
      connector: "Non-Sparking Hook",
      standard: "EN 355, ESD Safe",
    },
    features: ["Anti-static properties", "ESD safe design", "Non-sparking hardware", "Electronics industry approved"],
    applications: [
      "Electronics manufacturing",
      "Explosive atmospheres",
      "Pharmaceutical facilities",
      "Chemical processing",
    ],
  },
  {
    id: "lan-011",
    name: "WL20DE Dielectric Lanyard",
    category: "lanyard",
    subcategory: "Specialty Lanyards",
    description: "Dielectric lanyard for electrical work",
    price: 4600,
    image: "/images/products/wl20de-lanyard.jpg",
    specifications: {
      material: "Dielectric Webbing",
      length: "2.0m",
      type: "Single Leg",
      connector: "Dielectric Hook",
      standard: "EN 355, Dielectric",
    },
    features: ["Non-conductive materials", "Electrical work rated", "No metal components", "High voltage protection"],
    applications: ["Electrical maintenance", "Power line work", "Substation work", "Utility operations"],
  },
  {
    id: "lan-012",
    name: "WL22 DE Double Leg Dielectric Lanyard",
    category: "lanyard",
    subcategory: "Specialty Lanyards",
    description: "Double leg dielectric lanyard for electrical safety",
    price: 5400,
    image: "/images/products/wl22-de-lanyard.jpg",
    specifications: {
      material: "Dielectric Webbing",
      length: "1.8m",
      type: "Double Leg",
      connector: "Dielectric Hook",
      standard: "EN 355, Dielectric",
    },
    features: [
      "Complete dielectric protection",
      "Double leg for 100% tie-off",
      "Non-metallic construction",
      "High visibility color",
    ],
    applications: ["High voltage work", "Electrical testing", "Power distribution", "Electrical construction"],
  },
  // Work Positioning Lanyards
  {
    id: "lan-013",
    name: "WPL-P Work Positioning Lanyard (Pole Strap)",
    category: "lanyard",
    subcategory: "Work Positioning Lanyards",
    description: "Adjustable work positioning lanyard for pole work",
    price: 3400,
    image: "/images/products/wpl-p-positioning.jpg",
    featured: true,
    specifications: {
      material: "Polyester Webbing",
      length: "Adjustable 1.2m-2.0m",
      type: "Work Positioning",
      connector: "Double Locking Snap Hooks",
      standard: "EN 358",
    },
    features: [
      "Adjustable length design",
      "Work positioning approved",
      "Hands-free working",
      "Heavy duty construction",
    ],
    applications: ["Utility pole work", "Tree surgery", "Transmission towers", "Street lighting"],
  },
  {
    id: "lan-014",
    name: "WPL-B Work Positioning Belt Lanyard",
    category: "lanyard",
    subcategory: "Work Positioning Lanyards",
    description: "Work positioning lanyard with belt attachment",
    price: 3200,
    image: "/images/products/wpl-b-positioning.jpg",
    specifications: {
      material: "Polyester Webbing",
      length: "Adjustable 1.5m-2.5m",
      type: "Work Positioning",
      connector: "Scaffold Hooks",
      standard: "EN 358",
    },
    features: ["Belt attachment points", "Wide adjustment range", "Comfortable positioning", "Durable connectors"],
    applications: ["Steel erection", "Façade work", "Wind turbine installation", "Industrial maintenance"],
  },
  {
    id: "lan-015",
    name: "WPL02 Short Work Positioning Lanyard",
    category: "lanyard",
    subcategory: "Work Positioning Lanyards",
    description: "Short adjustable work positioning lanyard",
    price: 2800,
    image: "/images/products/wpl02-positioning.jpg",
    specifications: {
      material: "Webbing",
      length: "Adjustable 0.8m-1.2m",
      type: "Work Positioning",
      connector: "Snap Hooks",
      standard: "EN 358",
    },
    features: ["Compact short length", "Quick adjustment system", "Close work positioning", "Lightweight design"],
    applications: ["Confined space work", "Close proximity work", "Vehicle maintenance", "Equipment installation"],
  },
  {
    id: "lan-016",
    name: "WPL03 Restraint Positioning Lanyard",
    category: "lanyard",
    subcategory: "Work Positioning Lanyards",
    description: "Work positioning and restraint lanyard combination",
    price: 3600,
    image: "/images/products/wpl03-positioning.jpg",
    specifications: {
      material: "High Strength Webbing",
      length: "Adjustable 1.0m-1.8m",
      type: "Work Positioning/Restraint",
      connector: "Double Action Hooks",
      standard: "EN 358, EN 354",
    },
    features: ["Dual purpose design", "Work restraint capability", "Positioning support", "Heavy duty hardware"],
    applications: ["Roof edge work", "Platform work", "Leading edge protection", "Restricted areas"],
  },
  {
    id: "lan-017",
    name: "PL01 Coiled Cable Positioning Lanyard",
    category: "lanyard",
    subcategory: "Work Positioning Lanyards",
    description: "Coiled steel cable work positioning lanyard",
    price: 4200,
    image: "/images/products/pl01-coiled.jpg",
    specifications: {
      material: "Coiled Steel Cable",
      length: "1.5m (extends to 3.0m)",
      type: "Work Positioning",
      connector: "Swivel Snap Hooks",
      standard: "EN 358",
    },
    features: ["Coiled cable design", "Self-retracting function", "Minimal snagging", "High durability"],
    applications: ["Telecom work", "Tower climbing", "Mobile work platforms", "Aerial work"],
  },
  // Tool Lanyards
  {
    id: "lan-018",
    name: "TL-01 Single Tool Lanyard",
    category: "lanyard",
    subcategory: "Tool Lanyards",
    description: "Tool lanyard for dropped object prevention",
    price: 800,
    image: "/images/products/tl01-tool-lanyard.jpg",
    featured: true,
    specifications: {
      material: "Elastic Cord",
      length: "0.8m-1.2m (Expandable)",
      capacity: "Up to 5kg",
      attachment: "Carabiner and Tool Loop",
      standard: "Dropped Object Prevention",
    },
    features: ["Elastic cord prevents drops", "Carabiner attachment", "Tool loop connector", "High visibility orange"],
    applications: ["Work at height tool safety", "Construction sites", "Industrial maintenance", "Offshore platforms"],
  },
  {
    id: "lan-019",
    name: "TL-02 Dual Tool Lanyard",
    category: "lanyard",
    subcategory: "Tool Lanyards",
    description: "Dual tool lanyard with two attachment points",
    price: 1200,
    image: "/images/products/tl02-tool-lanyard.jpg",
    specifications: {
      material: "Elastic Cord",
      length: "0.8m-1.2m (Expandable)",
      capacity: "Up to 10kg combined",
      attachment: "Dual Tool Loops",
      standard: "Dropped Object Prevention",
    },
    features: ["Two independent tool attachments", "Elastic design", "Prevents tool drops", "Easy clip-on system"],
    applications: ["Multi-tool operations", "Electrical work", "Plumbing at height", "Assembly work"],
  },
  {
    id: "lan-020",
    name: "TLAT-02 Retractable Tool Lanyard",
    category: "lanyard",
    subcategory: "Tool Lanyards",
    description: "Auto-retractable tool lanyard for heavy tools",
    price: 2400,
    image: "/images/products/tlat02-tool-lanyard.jpg",
    specifications: {
      material: "Steel Wire with Housing",
      length: "Retracts to 0.2m, extends to 1.5m",
      capacity: "Up to 15kg",
      attachment: "Swivel Carabiner",
      standard: "Dropped Object Prevention",
    },
    features: [
      "Auto-retractable mechanism",
      "Heavy tool capacity",
      "Swivel carabiner prevents tangling",
      "Durable steel construction",
    ],
    applications: [
      "Heavy tool operations",
      "Power tool work at height",
      "Industrial construction",
      "Equipment maintenance",
    ],
  },
]
