import type { Product } from "../types"

export const powerToolsProducts: Product[] = [
  {
    id: "pt-001",
    name: "Bosch GWS 750 Angle Grinder",
    category: "power-tools",
    subcategory: "Angle Grinders",
    brand: "Bosch",
    description: "Professional 750W angle grinder for cutting and grinding",
    image: "/images/products/bosch-gws750-grinder.jpg",
    features: ["750W motor", "115mm disc", "Adjustable guard", "Soft grip handle"],
    applications: ["Metal cutting", "Grinding", "Surface preparation", "Construction"],
  },
  {
    id: "pt-002",
    name: "Black+Decker UM100 Oscillating Saw",
    category: "power-tools",
    subcategory: "Multi-Tools",
    brand: "Black+Decker",
    description: "Versatile oscillating multi-tool for various cutting applications",
    image: "/images/products/blackdecker-ks501-jigsaw.jpg",
    features: ["300W motor", "Multiple blades", "Variable speed", "Dust collection"],
    applications: ["Precision cutting", "DIY work", "Wood and metal", "Detail work"],
  },
  {
    id: "pt-003",
    name: "DeWalt DWD024 Power Drill",
    category: "power-tools",
    subcategory: "Cordless Drills",
    brand: "DeWalt",
    description: "Reliable compact power drill for general drilling and fastening",
    image: "/images/products/dewalt-dwd024-drill.jpg",
    features: ["500W motor", "13mm chuck", "Variable speed", "Lightweight design"],
    applications: ["Drilling holes", "Fastening", "Wood and plastics", "General maintenance"],
  },
  {
    id: "pt-004",
    name: "Stanley STEL311 Hand Saw",
    category: "power-tools",
    subcategory: "Saws",
    brand: "Stanley",
    description: "Professional hand saw for precise straight cuts",
    image: "/images/products/stanley-stel311-saw.jpg",
    features: ["High carbon steel blade", "Comfortable handle", "Sharp teeth", "Precision cutting"],
    applications: ["Wood cutting", "Carpentry", "Precision work", "Detail finishing"],
  },
  {
    id: "pt-005",
    name: "DeWalt Rotary Drill DCD996B",
    category: "power-tools",
    subcategory: "Cordless Drills",
    brand: "DeWalt",
    description: "Compact and lightweight 20V MAX cordless rotary drill for professional applications",
    image: "/images/products/dewalt-dcd996b-rotary-drill.jpg",
    features: ["20V MAX XR Li-Ion compact design", "2-speed transmission", "1/2\" single sleeve chuck", "LED work light", "Compact and lightweight design"],
    applications: ["Drilling in wood and metal", "Fastening applications", "Construction work", "General maintenance", "Professional contractors"],
  },
  {
    id: "pt-006",
    name: "Die Grinder - DG327NTC",
    category: "power-tools",
    subcategory: "Die Grinders",
    brand: "Professional",
    description: "Precision handheld die grinder for detailed grinding and polishing work",
    image: "/images/products/die-grinder-dg327ntc.jpg",
    features: ["Precision grinding capability", "Polishing capability", "Professional grade", "Ergonomic design", "Rotary action"],
    applications: ["Precision grinding", "Polishing", "Detail work", "Metal finishing", "Professional tooling"],
  },
  {
    id: "pt-007",
    name: "Bench Grinder - BG40",
    category: "power-tools",
    subcategory: "Bench Grinders",
    brand: "Professional",
    description: "Industrial grade dual wheel bench grinder for sharpening and grinding",
    image: "/images/products/bench-grinder-bg40.jpg",
    features: ["Dual wheels", "Industrial grade", "Sharpening capability", "Bench mounted", "Heavy duty construction"],
    applications: ["Tool sharpening", "Metal grinding", "Surface preparation", "Tool maintenance", "Industrial workshop"],
  },
  {
    id: "pt-008",
    name: "Polisher - Variable Speed - GPO13-35",
    category: "power-tools",
    subcategory: "Polishers",
    brand: "Professional",
    description: "Professional variable speed polisher for buffing and polishing applications",
    image: "/images/products/polisher-gpo13-35.jpg",
    features: ["Variable speed control", "Buffing capability", "Professional grade", "Ergonomic grip", "Precision polishing"],
    applications: ["Metal polishing", "Surface finishing", "Buffing", "Paint correction", "Professional detailing"],
  },
]
