import type { Product } from "../types"

export const powerToolsProducts: Product[] = [
  {
    id: "pt-001",
    name: "Bosch GWS 750 Angle Grinder",
    category: "power-tools",
    brand: "Bosch",
    description: "Professional 750W angle grinder for cutting and grinding",
    image: "/images/products/bosch-gws750-grinder.jpg",
    features: ["750W motor", "115mm disc", "Adjustable guard", "Soft grip handle"],
    applications: ["Metal cutting", "Grinding", "Surface preparation", "Construction"],
  },
  {
    id: "pt-002",
    name: "Black+Decker UM100 Oscillating Saw",
    category: "power-tools",
    brand: "Black+Decker",
    description: "Versatile oscillating multi-tool for various cutting applications",
    image: "/images/products/blackdecker-ks501-jigsaw.jpg",
    features: ["300W motor", "Multiple blades", "Variable speed", "Dust collection"],
    applications: ["Precision cutting", "DIY work", "Wood and metal", "Detail work"],
  },
  {
    id: "pt-003",
    name: "DeWalt DWD024 Power Drill",
    category: "power-tools",
    brand: "DeWalt",
    description: "Reliable compact power drill for general drilling and fastening",
    image: "/images/products/dewalt-dwd024-drill.jpg",
    features: ["500W motor", "13mm chuck", "Variable speed", "Lightweight design"],
    applications: ["Drilling holes", "Fastening", "Wood and plastics", "General maintenance"],
  },
  {
    id: "pt-004",
    name: "Stanley STEL311 Hand Saw",
    category: "power-tools",
    brand: "Stanley",
    description: "Professional hand saw for precise straight cuts",
    image: "/images/products/stanley-stel311-saw.jpg",
    features: ["High carbon steel blade", "Comfortable handle", "Sharp teeth", "Precision cutting"],
    applications: ["Wood cutting", "Carpentry", "Precision work", "Detail finishing"],
  },
  {
    id: "pt-005",
    name: "DeWalt Rotary Drill DCD996B",
    category: "power-tools",
    brand: "DeWalt",
    description: "Compact and lightweight 20V MAX cordless rotary drill for professional applications",
    image: "/images/products/dewalt-dcd996b-rotary-drill.jpg",
    features: ["20V MAX XR Li-Ion compact design", "2-speed transmission", "1/2\" single sleeve chuck", "LED work light", "Compact and lightweight design"],
    applications: ["Drilling in wood and metal", "Fastening applications", "Construction work", "General maintenance", "Professional contractors"],
  },
]
