-- Insert LANYARD products
INSERT INTO public.products (id, name, category, subcategory, description, price, image, featured, specifications, features, applications)
VALUES
  -- Rope Lanyards
  ('lan-001', 'RL22 Double Leg Rope Lanyard', 'lanyard', 'Rope Lanyards', 'Double leg rope lanyard with shock absorber for fall protection', 2800, '/images/products/rl22-rope-lanyard.jpg', true, '{"material": "Nylon Rope", "length": "1.8m", "type": "Double Leg", "connector": "Snap Hook", "standard": "EN 355"}', ARRAY['Integrated shock absorber', 'Double leg design for 100% tie-off', 'Durable nylon rope construction', 'Corrosion-resistant hardware'], ARRAY['Construction work at height', 'Tower climbing', 'Industrial maintenance', 'Scaffolding work']),
  
  ('lan-002', 'RL61 Single Leg Rope Lanyard', 'lanyard', 'Rope Lanyards', 'Single leg rope lanyard with shock absorber', 1800, '/images/products/rl61-rope-lanyard.jpg', false, '{"material": "Nylon Rope", "length": "1.8m", "type": "Single Leg", "connector": "Snap Hook", "standard": "EN 355"}', ARRAY['Integrated shock absorber', 'Lightweight design', 'High strength rope', 'Easy to use snap hooks'], ARRAY['General work at height', 'Maintenance work', 'Confined space entry', 'Temporary access']),
  
  -- Braided Lanyards
  ('lan-003', 'BL22 Double Leg Braided Lanyard', 'lanyard', 'Braided Lanyards', 'Double leg braided lanyard with energy absorber', 3200, '/images/products/bl22-braided-lanyard.jpg', true, '{"material": "Braided Polyester", "length": "1.8m", "type": "Double Leg", "connector": "Scaffold Hook", "standard": "EN 355"}', ARRAY['High abrasion resistance', 'Double leg for continuous protection', 'Energy absorbing system', 'UV resistant material'], ARRAY['Heavy duty construction', 'Steel erection', 'Bridge work', 'Industrial applications']),
  
  ('lan-004', 'BL61 Single Leg Braided Lanyard', 'lanyard', 'Braided Lanyards', 'Single leg braided lanyard for fall protection', 2200, '/images/products/bl61-braided-lanyard.jpg', false, '{"material": "Braided Polyester", "length": "1.8m", "type": "Single Leg", "connector": "Snap Hook", "standard": "EN 355"}', ARRAY['Durable braided construction', 'Shock absorber included', 'Weather resistant', 'Compact design'], ARRAY['Construction sites', 'Wind turbine maintenance', 'Roofing work', 'General industrial use']),
  
  ('lan-005', 'BL80 Heavy Duty Braided Lanyard', 'lanyard', 'Braided Lanyards', 'Heavy duty single leg braided lanyard with 80kg capacity', 2600, '/images/products/bl80-braided-lanyard.jpg', false, '{"material": "Heavy Duty Braided Polyester", "length": "1.8m", "type": "Single Leg", "connector": "Heavy Duty Hook", "capacity": "80kg", "standard": "EN 355"}', ARRAY['Extra heavy duty construction', 'Higher weight capacity', 'Reinforced shock absorber', 'Industrial grade hardware'], ARRAY['Heavy equipment operation', 'Industrial construction', 'Mining operations', 'Heavy duty applications']),
  
  -- Webbing Lanyards
  ('lan-006', 'WL22 Double Leg Webbing Lanyard', 'lanyard', 'Webbing Lanyards', 'Double leg webbing lanyard with shock absorber', 2400, '/images/products/wl22-webbing-lanyard.jpg', false, '{"material": "Polyester Webbing", "length": "1.8m", "type": "Double Leg", "connector": "Snap Hook", "standard": "EN 355"}', ARRAY['Comfortable webbing material', 'Visual wear indicators', 'Lightweight and flexible', 'Easy inspection'], ARRAY['Construction', 'Maintenance', 'Inspection work', 'General access']),
  
  -- Elastic Lanyards
  ('lan-007', 'EL22 Double Leg Elastic Lanyard', 'lanyard', 'Elastic Lanyards', 'Double leg elastic lanyard with stretch capacity', 3400, '/images/products/el22-elastic-lanyard.jpg', false, '{"material": "Elastic Polyester", "length": "1.2m-1.8m", "type": "Double Leg", "connector": "Snap Hook", "standard": "EN 355"}', ARRAY['Stretchable design reduces trip hazards', 'Reduces risk of snagging', 'Energy absorber included', 'Compact when not extended'], ARRAY['Confined spaces', 'Cluttered work areas', 'Moving platforms', 'Crane operation']),
  
  ('lan-008', 'EL61 Single Leg Elastic Lanyard', 'lanyard', 'Elastic Lanyards', 'Single leg elastic lanyard for confined spaces', 2400, '/images/products/el61-elastic-lanyard.jpg', false, '{"material": "Elastic Polyester", "length": "1.2m-1.8m", "type": "Single Leg", "connector": "Snap Hook", "standard": "EN 355"}', ARRAY['Self-retracting design', 'Minimizes fall distance', 'Reduces nuisance length', 'Lightweight'], ARRAY['Confined space work', 'Indoor maintenance', 'Equipment access', 'Close quarter work']),
  
  -- Specialty Lanyards
  ('lan-009', 'WL22-FR Flame Resistant Lanyard', 'lanyard', 'Specialty Lanyards', 'Flame resistant webbing lanyard for hot work', 4200, '/images/products/wl22-fr-lanyard.jpg', true, '{"material": "Flame Resistant Webbing", "length": "1.8m", "type": "Double Leg", "connector": "Heat Resistant Hook", "rating": "Flame Resistant"}', ARRAY['Flame resistant material', 'High temperature resistant hardware', 'Suitable for welding areas', 'Maintains strength in heat'], ARRAY['Welding work', 'Hot work operations', 'Furnace maintenance', 'Foundry operations']),
  
  ('lan-010', 'WL20AS Anti-Static Lanyard', 'lanyard', 'Specialty Lanyards', 'Anti-static lanyard for electronics work', 3800, '/images/products/wl20-as-lanyard.jpg', false, '{"material": "Conductive Webbing", "length": "2.0m", "type": "Single Leg", "connector": "Snap Hook", "resistance": "<1 MΩ"}', ARRAY['Anti-static properties', 'Protects sensitive equipment', 'Conductive webbing', 'Static dissipative'], ARRAY['Electronics manufacturing', 'Clean room operations', 'Explosive atmosphere', 'Sensitive equipment areas']),
  
  ('lan-011', 'WL20DE Dielectric Lanyard', 'lanyard', 'Specialty Lanyards', 'Dielectric lanyard for electrical work', 4800, '/images/products/wl20-de-lanyard.jpg', false, '{"material": "Dielectric Webbing", "length": "2.0m", "type": "Single Leg", "connector": "Dielectric Hook", "rating": "Insulated to 30kV"}', ARRAY['Non-conductive materials', 'Electrical insulation', 'Arc flash rated', 'No metal components'], ARRAY['Electrical utility work', 'Substation maintenance', 'High voltage areas', 'Electrical installation']),
  
  ('lan-012', 'WL22-DE Dielectric Double Leg Lanyard', 'lanyard', 'Specialty Lanyards', 'Double leg dielectric lanyard for continuous protection', 5400, '/images/products/wl22-de-lanyard.jpg', false, '{"material": "Dielectric Webbing", "length": "2.2m", "type": "Double Leg", "connector": "Dielectric Hook", "rating": "Insulated to 30kV"}', ARRAY['100% tie-off capability', 'Non-conductive throughout', 'High voltage insulation', 'Arc flash protection'], ARRAY['Electrical maintenance', 'Power line work', 'Transformer servicing', 'Electrical construction']),
  
  -- Work Positioning Lanyards
  ('lan-013', 'WPL-P Pole Strap Work Positioning', 'lanyard', 'Work Positioning Lanyards', 'Adjustable pole strap for positioning', 2800, '/images/products/wpl-p-positioning.jpg', false, '{"material": "Heavy Duty Webbing", "length": "Adjustable 1.2m-2.4m", "type": "Positioning", "connector": "D-ring", "capacity": "140kg"}', ARRAY['Hands-free positioning', 'Adjustable length', 'Comfort padding available', 'Quick adjustment system'], ARRAY['Utility pole work', 'Tree trimming', 'Tower maintenance', 'Telecom installation']),
  
  ('lan-014', 'WPL-B Beam Work Positioning Lanyard', 'lanyard', 'Work Positioning Lanyards', 'Work positioning lanyard for beam work', 3200, '/images/products/wpl-b-positioning.jpg', false, '{"material": "Wire Core Webbing", "length": "1.8m", "type": "Positioning", "connector": "Steel Hook", "capacity": "140kg"}', ARRAY['Wire core for rigidity', 'Prevents sliding', 'Steel connectors', 'Durable construction'], ARRAY['Steel erection', 'Beam walking', 'Bridge construction', 'Structural work']),
  
  ('lan-015', 'WPL02 Restraint Positioning Lanyard', 'lanyard', 'Work Positioning Lanyards', 'Short restraint lanyard to prevent falls', 1800, '/images/products/wpl02-restraint.jpg', false, '{"material": "Webbing", "length": "0.6m", "type": "Restraint", "connector": "Snap Hook", "capacity": "140kg"}', ARRAY['Restricts movement to safe zone', 'Short length prevents falls', 'Lightweight design', 'Easy to connect'], ARRAY['Leading edge work', 'Roof work', 'Platform edges', 'Restricted access areas']),
  
  ('lan-016', 'WPL03 Twin Tail Positioning', 'lanyard', 'Work Positioning Lanyards', 'Twin tail for 100% connection', 3600, '/images/products/wpl03-twin-tail.jpg', false, '{"material": "Webbing", "length": "1.8m each leg", "type": "Twin Tail", "connector": "Snap Hook", "capacity": "140kg"}', ARRAY['Always connected safety', 'Individual leg adjustment', 'Dual connection points', 'Continuous protection'], ARRAY['Moving between anchors', 'Ladder climbing', 'Scaffold access', 'Multi-point work']),
  
  ('lan-017', 'PL01 Coiled Cable Positioning', 'lanyard', 'Work Positioning Lanyards', 'Coiled cable work positioning lanyard', 4200, '/images/products/pl01-coiled-cable.jpg', false, '{"material": "Steel Cable", "length": "1.5m-4.5m coiled", "type": "Positioning", "connector": "Carabiner", "capacity": "140kg"}', ARRAY['Self-retracting coiled design', 'Reduces trip hazards', 'Steel cable construction', 'High durability'], ARRAY['Vehicle maintenance', 'Aircraft servicing', 'Equipment operation', 'Mobile platform work']),
  
  -- Tool Lanyards
  ('lan-018', 'TL-01 Single Tool Lanyard', 'lanyard', 'Tool Lanyards', 'Tool lanyard for dropped object prevention', 800, '/images/products/tl-01-tool-lanyard.jpg', false, '{"material": "Elastic Cord", "length": "0.9m", "capacity": "2kg", "connector": "Carabiner + Tool Loop"}', ARRAY['Prevents dropped tools', 'Elastic cord stretches to 1.5m', 'Lightweight and compact', 'Easy attachment'], ARRAY['Work at height with tools', 'Offshore platforms', 'Construction', 'Industrial maintenance']),
  
  ('lan-019', 'TL-02 Heavy Duty Tool Lanyard', 'lanyard', 'Tool Lanyards', 'Heavy duty tool lanyard for larger tools', 1200, '/images/products/tl-02-tool-lanyard.jpg', false, '{"material": "Webbing + Steel Cable", "length": "1.0m", "capacity": "10kg", "connector": "Heavy Duty Carabiner"}', ARRAY['Supports heavy tools', 'Reinforced construction', 'Dual attachment points', 'High strength cable'], ARRAY['Heavy tool operations', 'Industrial work', 'Mining', 'Heavy construction']),
  
  ('lan-020', 'TLAT-02 Adjustable Tool Tether', 'lanyard', 'Tool Lanyards', 'Adjustable tool tether with multiple attachment points', 1600, '/images/products/tlat-02-tool-tether.jpg', false, '{"material": "Dyneema Webbing", "length": "Adjustable 0.5m-1.2m", "capacity": "5kg", "connector": "Multiple Loops"}', ARRAY['Adjustable length', 'Multiple tool attachment', 'Ultra-light Dyneema', 'Quick release system'], ARRAY['Multiple tool operations', 'Precision work at height', 'Telecommunications', 'Electrical work'])
ON CONFLICT (id) DO NOTHING;
