-- Harness Products Migration
-- This script inserts all harness products from harness.ts into the Supabase products table

INSERT INTO public.products (id, name, category, subcategory, description, image, features, applications, brand, created_at, updated_at)
VALUES
  ('har-001', 'VAYU YU01 Full Body Harness', 'harness', 'Professional Grade Harnesses', 'Premium professional-grade full body harness with advanced comfort padding and multiple D-rings for versatile fall protection applications', 'https://udyogisafety.com/wp-content/uploads/2020/02/191202-027-VAYU.jpg', ARRAY['Premium padded shoulder straps for all-day comfort', 'Multiple attachment points (dorsal, sternal, lateral)', 'Quick-connect buckle system for easy donning', 'Heavy-duty webbing with reinforced stitching', 'Complies with EN 361 and IS 3521 standards'], ARRAY['Construction and building work', 'Telecom tower climbing', 'Wind turbine maintenance', 'Industrial maintenance', 'Fall arrest systems'], 'Udyogi Safety', NOW(), NOW()),
  ('har-002', 'ULTRATEK Full Body Harness', 'harness', 'Professional Grade Harnesses', 'Ultra-lightweight yet robust full body harness designed for maximum mobility and comfort during extended use', 'https://udyogisafety.com/wp-content/uploads/2020/02/Ultratek.jpg', ARRAY['Lightweight construction reduces fatigue', 'Breathable padding for hot environments', 'One dorsal and two sternal D-rings', 'Quick-adjust leg and chest straps', 'Reflective strips for visibility'], ARRAY['Scaffolding work', 'Confined space entry', 'Roofing applications', 'Steel erection', 'General fall protection'], 'Udyogi Safety', NOW(), NOW()),
  ('har-003', 'TRIVAGO Full Body Harness', 'harness', 'Professional Grade Harnesses', 'Three-point adjustment full body harness offering excellent weight distribution and comfort for industrial applications', 'https://udyogisafety.com/wp-content/uploads/2020/02/191202-024-Trivago.jpg', ARRAY['Three-point adjustment system', 'Padded waist belt for load distribution', 'Corrosion-resistant hardware', 'Color-coded adjustment points', 'Meets international safety standards'], ARRAY['Industrial maintenance', 'Construction sites', 'Warehouse operations', 'Utility work', 'Emergency rescue'], 'Udyogi Safety', NOW(), NOW()),
  ('har-004', 'ECO 1 Full Body Harness', 'harness', 'Economical Harnesses', 'Cost-effective full body harness providing essential fall protection for light-duty applications', 'https://udyogisafety.com/wp-content/uploads/2020/02/210514-001-ECO-1.jpg', ARRAY['Economical design without compromising safety', 'Single dorsal D-ring attachment', 'Adjustable leg and chest straps', 'Lightweight polyester webbing', 'Easy to use and maintain'], ARRAY['Light construction work', 'Basic fall protection', 'Maintenance tasks', 'Short-duration work', 'Training purposes'], 'Udyogi Safety', NOW(), NOW()),
  ('har-005', 'ECO 2 Full Body Harness', 'harness', 'Economical Harnesses', 'Enhanced economical harness with improved padding and adjustment features', 'https://udyogisafety.com/wp-content/uploads/2023/06/ECO-2.jpg', ARRAY['Improved padding over ECO 1', 'Quick-release buckles', 'Durable webbing construction', 'Standard compliant', 'Color-coded straps'], ARRAY['General industrial use', 'Facility maintenance', 'Basic height work', 'Equipment installation', 'Light-duty fall arrest'], 'Udyogi Safety', NOW(), NOW()),
  ('har-006', 'ECO 3 Full Body Harness', 'harness', 'Economical Harnesses', 'Mid-range economical harness offering good comfort and protection balance', 'https://udyogisafety.com/wp-content/uploads/2023/06/ECO-3.jpg', ARRAY['Balanced comfort and economy', 'Reinforced stitching at critical points', 'Easy-adjust shoulder straps', 'Standard-compliant hardware', 'Suitable for regular use'], ARRAY['Regular industrial maintenance', 'Construction work', 'Utility operations', 'Building services', 'General fall protection'], 'Udyogi Safety', NOW(), NOW()),
  ('har-007', 'ECO 4 Full Body Harness', 'harness', 'Economical Harnesses', 'Advanced economical model with premium features at an affordable price', 'https://udyogisafety.com/wp-content/uploads/2023/06/ECO-4.jpg', ARRAY['Premium features at economical price', 'Enhanced padding for comfort', 'Multiple size adjustments', 'Durable construction', 'High-quality buckles'], ARRAY['Extended duration work', 'Industrial applications', 'Construction projects', 'Maintenance operations', 'Professional use'], 'Udyogi Safety', NOW(), NOW()),
  ('har-008', 'ECO 1/KG Full Body Harness with Vest', 'harness', 'High Visibility Vest Harnesses', 'High-visibility lime green vest-style harness combining fall protection with enhanced visibility for maximum safety', '/images/products/eco-1-kg-harness.jpg', ARRAY['Integrated high-visibility lime green vest', 'Reflective strips for 360-degree visibility', 'Comfortable vest construction', 'Full body fall protection', 'Meets visibility standards'], ARRAY['Road construction work', 'Traffic management', 'Low-light environments', 'Highway maintenance', 'Outdoor construction'], 'Udyogi Safety', NOW(), NOW()),
  ('har-009', 'ECO 1/KO Full Body Harness with Vest', 'harness', 'High Visibility Vest Harnesses', 'High-visibility orange vest-style harness for maximum visibility in demanding work environments', '/images/products/eco-1-ko-harness.jpg', ARRAY['Integrated high-visibility orange vest', 'Wide reflective strips', 'Breathable vest material', 'Full harness protection', 'Complies with visibility standards'], ARRAY['Highway construction', 'Traffic control', 'Emergency services', 'Railway maintenance', 'Airport operations'], 'Udyogi Safety', NOW(), NOW()),
  ('har-010', 'UB102 Full Body Harness', 'harness', 'Standard Industrial Harnesses', 'Reliable standard industrial harness designed for everyday use in various work environments', 'https://udyogisafety.com/wp-content/uploads/2023/06/UB102.jpg', ARRAY['Robust industrial-grade construction', 'Single dorsal D-ring', 'Adjustable leg loops', 'Durable polyester webbing', 'Standard-compliant design'], ARRAY['General industrial work', 'Manufacturing facilities', 'Warehousing', 'Maintenance operations', 'Construction sites'], 'Udyogi Safety', NOW(), NOW()),
  ('har-011', 'UB103 Full Body Harness', 'harness', 'Standard Industrial Harnesses', 'Enhanced industrial harness with sit-strap for prolonged suspension comfort', 'https://udyogisafety.com/wp-content/uploads/2020/02/210925-029-UB-103.jpg', ARRAY['Ideally positioned sit-strap for extended comfort', 'Premium webbing material', 'Reinforced attachment points', 'Quick-adjust buckles', 'Suitable for long-duration work'], ARRAY['Suspended access work', 'Prolonged work at height', 'Inspection tasks', 'Painting operations', 'Window cleaning'], 'Udyogi Safety', NOW(), NOW()),
  ('har-012', 'UB104 Full Body Harness', 'harness', 'Standard Industrial Harnesses', 'Four-point adjustment harness for customizable fit and comfort', 'https://udyogisafety.com/wp-content/uploads/2020/02/UB-104-4-POINT-HARNESS.jpg', ARRAY['Four-point adjustment system', 'Customizable fit for all body types', 'Heavy-duty D-ring', 'Padded shoulder straps', 'Industrial-strength construction'], ARRAY['Industrial maintenance', 'Construction work', 'Utility operations', 'Telecom work', 'General height safety'], 'Udyogi Safety', NOW(), NOW()),
  ('har-013', 'UB121 Full Body Harness', 'harness', 'Standard Industrial Harnesses', 'Advanced industrial harness with multiple attachment points for versatile applications', 'https://udyogisafety.com/wp-content/uploads/2020/02/UB-121-1.jpg', ARRAY['Multiple D-ring attachment points', 'Versatile configuration options', 'Premium quality webbing', 'Corrosion-resistant hardware', 'Ergonomic design'], ARRAY['Complex work positioning', 'Industrial rescue', 'Confined space work', 'Advanced fall protection', 'Multi-point anchorage'], 'Udyogi Safety', NOW(), NOW()),
  ('har-014', 'Tango II Full Body Harness', 'harness', 'Comfort Plus Harnesses', 'Premium comfort harness with advanced padding and ergonomic design for all-day wear', 'https://udyogisafety.com/wp-content/uploads/2020/02/Tango-II.jpg', ARRAY['Advanced comfort padding system', 'Ergonomic weight distribution', 'Premium quality materials', 'Multiple adjustment points', 'Breathable construction'], ARRAY['Extended duration work', 'Professional applications', 'Premium construction projects', 'High-end industrial facilities', 'Comfort-critical operations'], 'Udyogi Safety', NOW(), NOW()),
  ('har-015', 'UB102 Plus Full Body Harness', 'harness', 'Comfort Plus Harnesses', 'Enhanced version of UB102 with additional padding and comfort features', '/images/products/ub102-plus-harness.jpg', ARRAY['Enhanced padding over standard UB102', 'Improved comfort for long wear', 'Additional adjustment points', 'Premium buckle system', 'Superior weight distribution'], ARRAY['Long-duration industrial work', 'Professional construction', 'Extended maintenance tasks', 'Comfort-required applications', 'Premium project work'], 'Udyogi Safety', NOW(), NOW()),
  ('har-016', 'UB103 Plus Full Body Harness', 'harness', 'Comfort Plus Harnesses', 'Premium version of UB103 with enhanced sit-strap and comfort padding', '/images/products/ub103-plus-harness.jpg', ARRAY['Enhanced sit-strap with extra padding', 'Premium comfort construction', 'Advanced adjustment system', 'High-quality materials', 'Optimal for suspended work'], ARRAY['Extended suspended access', 'Premium inspection work', 'Long-duration painting', 'Professional window cleaning', 'Comfort-critical suspended tasks'], 'Udyogi Safety', NOW(), NOW()),
  ('har-017', 'UB102 FR Full Body Harness', 'harness', 'Flame Resistant Harnesses', 'Flame-resistant full body harness for hot work and welding applications', '/images/products/ub102-fr-harness.jpg', ARRAY['Flame-resistant webbing material', 'Heat-resistant hardware', 'Suitable for welding environments', 'Maintains strength in heat exposure', 'Complies with flame resistance standards'], ARRAY['Welding at heights', 'Hot work operations', 'Steel fabrication', 'Foundry work', 'High-temperature environments'], 'Udyogi Safety', NOW(), NOW()),
  ('har-018', 'VIDYUT UB102 DE Full Body Harness', 'harness', 'Electrical Safety Harnesses', 'Electrically insulated full body harness designed for electrical work and live line applications', 'https://udyogisafety.com/wp-content/uploads/2021/12/VIDYUT-UB102DE.jpg', ARRAY['Dielectric (non-conductive) webbing', 'Insulated hardware components', 'Suitable for electrical environments', 'Prevents electrical conductivity', 'Meets electrical safety standards'], ARRAY['Electrical maintenance', 'Power line work', 'Substation operations', 'Live electrical work', 'Utility electrical tasks'], 'Udyogi Safety', NOW(), NOW()),
  ('har-019', 'VIDYUT ULTRATEK DE Full Body Harness', 'harness', 'Electrical Safety Harnesses', 'Premium electrically insulated harness with advanced features for electrical safety', '/images/products/vidyut-ultratek-de-harness.jpg', ARRAY['Premium dielectric construction', 'Advanced insulation technology', 'Lightweight yet robust', 'Enhanced electrical protection', 'Professional-grade design'], ARRAY['High-voltage work', 'Electrical installation', 'Power transmission work', 'Critical electrical operations', 'Professional electrical tasks'], 'Udyogi Safety', NOW(), NOW()),
  ('har-020', 'UB102 AS Lite Full Body Harness', 'harness', 'Arc Flash Harnesses', 'Arc flash rated harness with anti-static properties for electrical hazard protection', '/images/products/ub102-as-lite-harness.jpg', ARRAY['Arc flash protection rating', 'Anti-static webbing material', 'Lightweight design', 'Electrical hazard protection', 'Static dissipative properties'], ARRAY['Arc flash environments', 'Electrical panel work', 'Switch gear operations', 'Electrical testing', 'High-risk electrical tasks'], 'Udyogi Safety', NOW(), NOW()),
  ('har-021', 'ULTRATEK AS Full Body Harness', 'harness', 'Arc Flash Harnesses', 'Premium arc flash and anti-static harness for advanced electrical safety', '/images/products/ultratek-as-harness.jpg', ARRAY['Advanced arc flash protection', 'Anti-static construction', 'Premium electrical safety features', 'Lightweight and comfortable', 'Professional electrical-grade'], ARRAY['Advanced electrical work', 'Arc flash rated areas', 'Critical electrical operations', 'Professional electrical tasks', 'High-hazard electrical environments'], 'Udyogi Safety', NOW(), NOW()),
  ('har-022', 'ULTRA-01 Full Body Harness', 'harness', 'Premium Leather Harnesses', 'Premium leather full body harness for heavy-duty industrial applications', 'https://udyogisafety.com/wp-content/uploads/2020/02/ULTRA-01.jpg', ARRAY['High-quality leather construction', 'Exceptional durability', 'Premium hardware', 'Professional-grade design', 'Long service life'], ARRAY['Heavy industrial work', 'Professional construction', 'Demanding environments', 'Premium applications', 'Long-term intensive use'], 'Udyogi Safety', NOW(), NOW()),
  ('har-023', 'ULTRA-02 Full Body Harness', 'harness', 'Premium Leather Harnesses', 'Advanced leather harness with enhanced features and comfort', '/images/products/ultra-02-harness.jpg', ARRAY['Premium leather with comfort padding', 'Advanced adjustment system', 'Heavy-duty construction', 'Superior quality hardware', 'Professional-grade materials'], ARRAY['Premium construction projects', 'Professional industrial work', 'High-quality applications', 'Demanding work environments', 'Long-duration heavy work'], 'Udyogi Safety', NOW(), NOW()),
  ('har-024', 'ULTRA-05 Full Body Harness', 'harness', 'Premium Leather Harnesses', 'Top-tier leather harness with maximum comfort and durability features', 'https://udyogisafety.com/wp-content/uploads/2020/02/ULTRA-05.jpg', ARRAY['Top-grade leather construction', 'Maximum comfort padding', 'Premium adjustment system', 'Exceptional durability', 'Professional quality'], ARRAY['Premium industrial applications', 'Professional construction', 'High-end projects', 'Executive-level safety', 'Comfort-critical heavy work'], 'Udyogi Safety', NOW(), NOW()),
  ('har-025', 'UK01 Lite Full Body Harness', 'harness', 'Lightweight Harnesses', 'Ultra-lightweight harness designed for maximum mobility and comfort', 'https://udyogisafety.com/wp-content/uploads/2020/02/UK01-Lite.jpg', ARRAY['Ultra-lightweight construction', 'Maximum mobility', 'Minimal bulk design', 'Quick-don features', 'Ideal for agile work'], ARRAY['Agile construction work', 'Quick access tasks', 'Mobile maintenance', 'Rapid response work', 'Lightweight-required applications'], 'Udyogi Safety', NOW(), NOW()),
  ('har-026', 'UK-04 Full Body Harness', 'harness', 'Lightweight Harnesses', 'Lightweight harness with four-point adjustment for comfort and mobility', 'https://udyogisafety.com/wp-content/uploads/2020/02/UK-04.jpg', ARRAY['Lightweight with adjustment features', 'Four-point adjustment', 'Comfortable for extended wear', 'Agile design', 'Quick-release buckles'], ARRAY['Mobile industrial work', 'Agile construction', 'Quick tasks at height', 'Maintenance operations', 'General lightweight applications'], 'Udyogi Safety', NOW(), NOW()),
  ('har-027', 'UK01 JKO Full Body Harness with Vest', 'harness', 'High Visibility Vest Harnesses', 'Lightweight harness with integrated high-visibility orange vest for maximum visibility and comfort', 'https://udyogisafety.com/wp-content/uploads/2023/06/UK01-JKO.jpg', ARRAY['Integrated high-visibility orange vest', 'Lightweight construction', 'Reflective strips for visibility', 'Comfortable vest design', 'Safety-focused architecture'], ARRAY['Road safety operations', 'Traffic management', 'Emergency services', 'Construction zones', 'Mobile maintenance'], 'Udyogi Safety', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;
